JiscSD/octopus

ui/src/pages/create.tsx
The purpose of this PR was to add dark mode option to the list of publication types.
=> Adding dark mode for publications in create

ui/src/pages/publications/[id]/index.tsx
The purpose of this PR was to remove the first name on the publication. I.e Nathan Sainsbury becomes N. Sainsbury
=> Remove first name from publication page

ui/src/components/Publication/Creation/StepFive.tsx, ui/src/layouts/BuildPublication.tsx, ui/src/lib/api.ts, ui/src/pages/publications/[id]/edit.tsx
The purpose of this PR was to finish the review & publish feature. 
Important to note, this PR does **not** include the link management & review section of the review process. 
This only covers the features that are already in place. 
This feature will need to be updated in a future PR when links are looked at.
[For Jira ticket 181](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-181)
---
User can review aggregate content submitted at all stages
User can return to make changes after viewing the review page
User can publish after viewing the review page. 
It is made clear that publishing is irreversible ie. cannot go back to draft.
---
https://user-images.githubusercontent.com/81176162/158228052-72ae9020-9c83-42d0-bf3a-a2b67a216bb5.mov
=> First run of review & publish process (oct-181)

README.md, api/prisma/migrations/20220404150333_/migration.sql, api/src/components/publication/controller.ts, api/src/components/publication/service.ts, api/src/components/rating/service.ts, api/src/lib/client.ts
The purpose of this PR was to return aggregate ratings for a given publication.
- Add `getAggregate` function that returns the aggregate grouped ratings for a publication
- Add `getOverall` function that returns the overall mean rating for a given publication
- Update `readme.md` to include clearer instructions on how to run locally
=> View ratings on an individual publication page

api/src/components/rating/controller.ts, api/src/lib/interface.ts
=> More updates

api/package-lock.json, api/package.json, ui/.eslintrc.json, ui/package-lock.json, ui/package.json, ui/src/pages/_app.tsx, ui/src/pages/_document.tsx
The purpose of this PR was to directly address some open issues:
#114 
#119
#71
Regarding #71 - This has shown a list of a11y warnings that need to be addressed in a future PR.
Also includes a minor version bump for Prisma.
=> Addressed #114 #119 #71

api/prisma/migrations/20220503122720_y/migration.sql, api/prisma/migrations/20220503124526_shauna/migration.sql, api/prisma/schema.prisma, api/prisma/seeds/bookmarkedPublications.ts, api/serverless.yml, api/src/components/bookmark/__tests__/getAllBookmarks.test.ts, api/src/components/bookmark/__tests__/getBookmark.test.ts, api/src/components/bookmark/controller.ts, api/src/components/bookmark/routes.ts, api/src/components/bookmark/service.ts, api/src/lib/interface.ts
The purpose of this PR is to create two endpoints, one which returns the bookmark for a specific publication that a user has created, and the other to return the publications a user has bookmarked. 
This PR request contains a change to the schema, the tests for both endpoints, additional seed data, an updated Serverless file and the creation of the endpoints (controller/ route) etc.
I have created two different endpoints that look like this (neither of which take a body):
- One which returns just the bookmark for a publication 
Path: `GET /publications/{id}/bookmark`
Successful response: 
```json
{
"id": "bookmark-2",
"publicationId": "publication-hypothesis-live",
"userId": "test-user-3"
}
```
Unsuccessful response: 
```json
false
```
- And another that returns an array of bookmarks that …
=> Get bookmark- API 

ui/src/components/Alert/index.tsx, ui/src/components/Nav/index.tsx, ui/src/components/Publication/SidebarCard/Actions/index.tsx, ui/src/components/Publication/SidebarCard/General/index.tsx, ui/src/pages/publications/[id]/flag/[flagId]/index.tsx, ui/src/pages/publications/[id]/index.tsx, ui/src/pages/verify.tsx
Fixes to 3 open issues (see issue list to the right).
=> UI bug fixes 20 05 2022

ui/package.json, ui/src/components/Alert/index.tsx, ui/src/components/Publication/Creation/CoAuthorEntry/index.tsx, ui/src/components/Publication/Creation/MainText.tsx, ui/src/components/Publication/SidebarCard/Actions/index.tsx, ui/src/components/Publication/SidebarCard/Ratings/index.tsx, ui/src/config/urls.ts, ui/src/lib/api.ts, ui/src/pages/index.tsx, ui/src/pages/publications/[id]/index.tsx, ui/src/stores/auth.ts, ui/src/stores/globals.ts, ui/src/stores/preferences.ts, ui/src/stores/publicationCreation.ts, ui/src/stores/toast.ts
The purpose of this PR was to fix the bugs surrounding the publication page.
Issue #149 
- Now correctly dynamically populates all publication data using swr.
- After creating a red flag, the red flag banner will reactively appear.
- Restyled the red flag banner slightly after having a chat with @lharre.
Changes I've made outside of the scope of this PR:
- Improved UX on the 'short description' and 'keywords' field in the create publication form, by adding a dynamic character count as well as some basic validation (max length of 160 on short desc field).
- Fixed a typo.
---
- Publication page should now be fully dynamic.
---
N/A
---
Character count:
https://user-images.githubusercontent.com/41571971/174570175-a6d3c8bc-723f-4164-a6dc-66b97217ab10.mov
=> OCT-issue-149

ui/src/components/Header/index.tsx, ui/src/components/Publication/SidebarCard/General/index.tsx, ui/src/pages/publications/[id]/index.tsx
The purpose of this PR was
- Remove publication chain links as this has since been replaced with the publication viz.
- Removed affiliated organisations section.
- Fixed visual bug on the DOI link which was causing the text to flow outside of the container.
=> Publication page UI tweaks

ui/src/config/urls.ts, ui/src/pages/login.tsx
The purpose of this PR is to update the title to `Octopus | Built for Researchers`
---
As per [OCT-218](https://jiscdev.atlassian.net/browse/OCT-218)
=> OCT-218 Change Browser Tab Text

ui/src/components/Alert/index.tsx, ui/src/components/Publication/SidebarCard/Actions/index.tsx, ui/src/components/Publication/SidebarCard/General/index.tsx
The purpose of this PR is to enhance the sidebar and ensure consistency throughout. 
---
As per [OCT-221](https://jiscdev.atlassian.net/browse/OCT-221)
=> Oct-221 Behaviour of peer review link for non-logged in users

api/src/lib/helpers.ts
fixing the URL we pass to datacite to use the id not the full doi field
=> fix DOI URL field

ui/src/pages/faq.tsx
=> fix double privacy in path

README.md, api/README.md, api/src/components/publication/service.ts, api/src/components/verification/controller.ts, ui/README.md
The purpose of this PR was to provide updated documentation for the repository.
=> Documentation update

ui/src/components/Button/index.tsx, ui/src/components/Publication/Creation/CoAuthor.tsx, ui/src/components/RORForm/index.tsx, ui/src/layouts/BuildPublication.tsx, ui/src/lib/types.ts
The purpose of this PR was to improve the UX of the publication process:
- Add a 'save' button to the bottom of every page
- Add a 'preview' button to the bottom of the 'review' page
- Add teal styling to 'preview' and 'publish' buttons
- Add green styling to 'save' button
- Add message to each step of publication flow - "Remember to save this draft before navigating away from the publication form."
- Changed where coauthor and affiliation button are located to a more noticeable position
=> Make buttons more prominent (OCT-243) - UI

README.md, api/README.md
The purpose of this PR was to update the README with explanations of issues I came across while setting up the environment.
=> Draft: Update README.md

ui/src/components/IconButton/index.tsx, ui/src/components/Publication/Creation/CoAuthor.tsx, ui/src/components/Publication/Creation/KeyInformation.tsx, ui/src/components/Publication/Creation/LinkedPublications.tsx, ui/src/components/Publication/Creation/MainText.tsx, ui/src/components/RORForm/index.tsx, ui/src/components/TextEditor/index.tsx, ui/src/components/Tooltip/index.tsx, ui/src/components/index.tsx, ui/src/layouts/BuildPublication.tsx, ui/tailwind.config.js
The purpose of this PR was to find an efficient way to display publication form action buttons and improve the Side Bar navigation on mobile
---
As per [OCT-331](https://jiscdev.atlassian.net/browse/OCT-331)
---
=> OCT-331 Resolve navigation display issues in publication form

ui/package-lock.json, ui/package.json, ui/src/components/Publication/Creation/MainText.tsx, ui/tsconfig.json
The purpose of this PR was to replace References textarea with a rich text editor and also update the references table to display html content
---
As per [OCT-350](https://jiscdev.atlassian.net/browse/OCT-350)
Will be added in a new commit
=> OCT-350 Rich text editor - field and table

ui/README.md
=> fix links in readme as mosly broken

ui/package-lock.json, ui/package.json, ui/src/components/Publication/Creation/MainText.tsx, ui/src/components/References/EditReferenceModal.tsx, ui/src/lib/helpers.tsx, ui/src/lib/interfaces.ts, ui/src/pages/faq.tsx, ui/src/pages/publications/[id]/index.tsx
The purpose of this PR was to extract and convert DOI strings into DOI URLs from the reference text.
---
As per [OCT-352](https://jiscdev.atlassian.net/browse/OCT-352)
---
=> OCT-352 DOI recognition

ui/src/config/urls.ts
The purpose of this PR was to enforce user login every time they try to login to ORCID so they can use a different account
---
As per [OCT-291](https://jiscdev.atlassian.net/browse/OCT-291)
---
=> OCT-291 User login - allow genuine logout

ui/src/config/urls.ts
Co-authored-by: Florin H <florin.holhos@wingravity.com>
---
---
---
=> added orcid login url parameters to enforce login (#255)

api/src/components/reference/controller.ts
=> Fix references compile error

ui/src/components/Publication/Creation/MainText.tsx, ui/src/components/References/EditReferenceModal.tsx, ui/src/pages/author-guide.tsx
The purpose of this PR was to update reference guidance text in order to match the current functionality
---
As per [OCT-381](https://jiscdev.atlassian.net/browse/OCT-381)
---
=> OCT-381 Update explanatory copy

ui/src/components/Publication/Creation/MainText.tsx, ui/src/components/RORForm/index.tsx, ui/src/pages/publications/[id]/index.tsx, ui/tailwind.config.js
The purpose of this PR was fix the post-review issues on references
---
As per [OCT-392](https://jiscdev.atlassian.net/browse/OCT-392)
---
=> OCT-392 Changes identified during .int testing

api/serverless.yml, api/src/components/authorization/controller.ts, api/src/components/authorization/routes.ts, ui/src/components/Header/index.tsx, ui/src/components/ORCID/LogInButton/index.tsx, ui/src/components/ORCID/LogOutButton/index.tsx, ui/src/config/endpoints.ts, ui/src/hooks/index.ts, ui/src/hooks/useAuthCheck.ts, ui/src/lib/helpers.tsx, ui/src/pages/_app.tsx, ui/src/pages/account.tsx, ui/src/pages/author-link.tsx, ui/src/pages/create.tsx, ui/src/pages/login.tsx, ui/src/pages/my-bookmarks.tsx, ui/src/pages/publications/[id]/edit.tsx, ui/src/pages/publications/[id]/flag/[flagId]/index.tsx, ui/src/pages/publications/[id]/index.tsx, ui/src/pages/verify.tsx
The purpose of this PR was to improve user authentication UX and handle JWT token expiry
---
As per [OCT-370](https://jiscdev.atlassian.net/browse/OCT-370)
---
=> OCT-370 Resolve immediate JWT issues

ui/src/hooks/useAuthCheck.ts, ui/src/pages/login.tsx
The purpose of this PR was to handle the "access_denied" error coming from ORCID, when a user denies access to his/her ORCID account.
---
As per [OCT-371](https://jiscdev.atlassian.net/browse/OCT-371)
---
=> OCT-371 ORCID - deny permission

ui/src/components/Publication/SidebarCard/Actions/index.tsx, ui/src/pages/login.tsx, ui/src/pages/verify.tsx
The purpose of this PR was to redirect the user to the verify email page after login, if they don't have a verified email
---
As per [OCT-373](https://jiscdev.atlassian.net/browse/OCT-373)
---
=> OCT-373 Email verification page shown after account setup

api/src/components/user/service.ts, api/src/lib/helpers.ts, ui/playwright.config.ts, ui/src/__testing__/LoggedIn/livePublication.e2e.spec.ts, ui/src/__testing__/LoggedIn/publish.e2e.spec.ts, ui/src/__testing__/PageModel.ts, ui/src/components/CommandPalette/index.tsx, ui/src/components/IconButton/index.tsx, ui/src/components/Publication/SidebarCard/Actions/index.tsx, ui/src/pages/login.tsx, ui/src/pages/search.tsx, ui/src/pages/verify.tsx
=> Merge MAIN into INT

seed-data-scripts/publication-metadata/package-lock.json, seed-data-scripts/publication-metadata/package.json, seed-data-scripts/publication-metadata/script.js
The purpose of this PR was to create a script which extracts the DOI URLs from a txt file and fetches the key citation metadata for each of them
---
---
---
=> OCT-394 Extract publication metadata from DOIs

infra/create-app/main.tf, infra/create-app/prod.tfvars, infra/modules/bastion/main.tf, infra/modules/bastion/vars.tf
to update the bastion servers to have static IPs and to synchronise the terraform with the changes made to shut down the servers overnight and to allow access via openvpn3 server
---
---
---
=> OCT-430 Update terraform

ui/src/pages/publications/[id]/index.tsx
The purpose of this PR was to add a new section with the parent problem(s) of a publication
---
As per [OCT-270](https://jiscdev.atlassian.net/browse/OCT-270)
---
=> OCT-270 Display parent problem(s) in problem hierarchy

ui/src/pages/publications/[id]/index.tsx
The purpose of this PR was to update linked problems sections titles on the publication page
---
As per [OCT-270](https://jiscdev.atlassian.net/browse/OCT-270)
---
BEFORE
AFTER
=> OCT-270 Display parent problem(s) in problem hierarchy (UPDATED TEXT)

ui/src/hooks/useAuthCheck.ts
The purpose of this PR was to solve the issue when a user logs in from a different browser tab and then comes back to an old tab, showing as logged out
---
As per [OCT-427](https://jiscdev.atlassian.net/browse/OCT-427)
---
=> OCT-427 UI out of sync while logged in

api/prisma/seed.ts, api/serverless.yml, api/src/components/link/controller.ts, api/src/components/link/routes.ts, api/src/components/link/service.ts, api/src/components/publication/service.ts, api/src/lib/interface.ts, api/src/utilities/seed.js, ui/package-lock.json
The purpose of this PR was to update the seed script, in order to allow for more data to be ingested by the system, on top of what is already there. This also allows for future data to be added as well.
---
- Update to reflect changes e.g. inclusion of references. 
- Skip data that has already been ingested. 
- Improved reporting e.g. failures, out of order data.
=> OCT-401 Update seed script

api/src/components/user/service.ts, ui/src/__tests__/components/Button.test.tsx, ui/src/__tests__/components/Publication/Creation/MainText.test.tsx, ui/src/__tests__/components/Users/SearchResult.test.tsx, ui/src/__tests__/test-utils.tsx, ui/src/components/Users/SearchResult/index.tsx, ui/src/lib/interfaces.ts
The purpose of this PR was to display current author affiliation(s) on authors search results page
---
As per [OCT-385](https://jiscdev.atlassian.net/browse/OCT-385)
---
=> OCT-385 Show affiliation in author search results

ui/src/__tests__/components/Button.test.tsx, ui/src/components/ActionCard/index.tsx, ui/src/components/Button/index.tsx, ui/src/components/Publication/Creation/CoAuthor.tsx, ui/src/components/Publication/Creation/DataStatements.tsx, ui/src/components/Publication/Creation/Funders.tsx, ui/src/components/Publication/Creation/KeyInformation.tsx, ui/src/components/Publication/Creation/LinkedPublications.tsx, ui/src/components/Publication/Creation/MainText.tsx, ui/src/components/RORForm/index.tsx, ui/src/components/References/AddReferences.tsx, ui/src/layouts/BuildPublication.tsx, ui/src/layouts/Error.tsx, ui/src/layouts/InformationLanding.tsx, ui/src/pages/about.tsx, ui/src/pages/browse.tsx, ui/src/pages/create.tsx, ui/src/pages/login.tsx, ui/src/pages/publications/[id]/flag/[flagId]/index.tsx
The purpose of this PR was to fix Button component when used as a link.
Added conditional prop for opening new tabs when user clicks on the link
---
As per [OCT-404](https://jiscdev.atlassian.net/browse/OCT-404)
Will add in a new commit
=> OCT-404 Browse publications/authors opens new tab

ui/package-lock.json, ui/package.json, ui/src/components/Publication/Visulization/index.tsx, ui/src/styles/globals.css, ui/tailwind.config.js
The purpose of this PR was to fix overlapping text in visualisation boxes
---
As per [OCT-388](https://jiscdev.atlassian.net/browse/OCT-388)
---
BEFORE
AFTER
=> OCT-388 Overlapping text in visualisation boxes

api/src/components/user/service.ts, ui/package-lock.json, ui/package.json, ui/src/__tests__/components/Button.test.tsx, ui/src/__tests__/components/Publication/Creation/MainText.test.tsx, ui/src/__tests__/components/Users/SearchResult.test.tsx, ui/src/__tests__/test-utils.tsx, ui/src/components/ActionCard/index.tsx, ui/src/components/Button/index.tsx, ui/src/components/Publication/Creation/CoAuthor.tsx, ui/src/components/Publication/Creation/DataStatements.tsx, ui/src/components/Publication/Creation/Funders.tsx, ui/src/components/Publication/Creation/KeyInformation.tsx, ui/src/components/Publication/Creation/LinkedPublications.tsx, ui/src/components/Publication/Creation/MainText.tsx, ui/src/components/Publication/Visulization/index.tsx, ui/src/components/RORForm/index.tsx, ui/src/components/References/AddReferences.tsx, ui/src/components/Users/SearchResult/index.tsx, ui/src/layouts/BuildPublication.tsx, ui/src/layouts/Error.tsx, ui/src/layouts/InformationLanding.tsx, ui/src/lib/interfaces.ts, ui/src/pages/about.tsx, ui/src/pages/browse.tsx, ui/src/pages/create.tsx, ui/src/pages/login.tsx, ui/src/pages/publications/[id]/flag/[flagId]/index.tsx, ui/tailwind.config.js
The purpose of this PR was to get the latest changes on int
---
---
---
=> Merging MAIN into INT

ui/src/components/Publication/Visulization/index.tsx, ui/src/layouts/Publication.tsx, ui/src/lib/helpers.tsx
The purpose of this PR was to make Visualization section on the Publication page visible on smaller devices by adding a horizontal scroll
---
As per [OCT-334](https://jiscdev.atlassian.net/browse/OCT-334)
---
BEFORE
AFTER
=> OCT-334 Switch to horizontal scroll for visualisation

api/src/components/user/service.ts
The purpose of this PR was to fix an issue with accounts, when first created/logged in, not adding their publics works to their Octopus profile.
---
[OCT-436](https://jiscdev.atlassian.net/browse/OCT-436?atlOrigin=eyJpIjoiNjJiY2MxYTUyYTM4NGFlZjk4MGQ4OTY3ZTlkYThjNGEiLCJwIjoiaiJ9)
=> OCT-436 - ORCID works not being pulled through

ui/src/components/Footer/index.tsx, ui/src/components/Publication/Creation/CoAuthor.tsx, ui/src/components/Publication/Creation/CoAuthorEntry/index.tsx, ui/src/components/Publication/Creation/KeyInformation.tsx, ui/src/components/Publication/Creation/LinkToEntry/index.tsx, ui/src/components/Publication/Creation/LinkedPublications.tsx, ui/src/components/Publication/Creation/MainText.tsx, ui/src/components/RORForm/index.tsx, ui/src/components/References/MenuBar.tsx, ui/src/components/RequiredIndicator/index.tsx, ui/src/components/TextEditor/index.tsx, ui/src/layouts/BuildPublication.tsx
The purpose of this PR was improve the accessibility of the edit publication pages.
---
- Fix accessibility issues identified by lighthouse on the main edit publication pages, mainly labels  on the button and the text  edit areas.
- Ideally also run another tool e.g. Axe to double check
=> OCT-428 Improve accessibility of edit publication pages

api/prisma/seed.ts, api/serverless.yml, api/src/components/link/controller.ts, api/src/components/link/routes.ts, api/src/components/link/service.ts, api/src/components/publication/controller.ts, api/src/components/publication/routes.ts, api/src/components/publication/service.ts, api/src/components/reference/controller.ts, api/src/lib/interface.ts, seed-data-scripts/seed/seed.js
The purpose of this PR was to add capability to add missing references.
---
As per [OCT-444](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-444)
=> OCT-444 Add capability to add missing references

seed-data-scripts/seed/seed.js
The purpose of this PR was fix errors that has been discovered during testing of seed ingest on int.octopus.ac
=> OCT-444 Fixes raised from int seed data ingest. 

infra/create-app/int.tfvars, infra/create-app/prod.tfvars, infra/modules/postgres/main.tf
The purpose of this PR was to upgrade postgres to version 14.5 as is on int.
---
Per [OCT-451](https://jiscdev.atlassian.net/browse/OCT-451?atlOrigin=eyJpIjoiNjEwZTVmNGI2YTQyNGM1NDlkYzQyNWExZWQ4MTg3ZmYiLCJwIjoiaiJ9)
=> OCT-451 - Update postgres (14.5)

docker-compose.yml, infra/modules/postgres/main.tf
The purpose of this PR was to update the local version of postgres to version 14.5 to match with RDS.
---
Postgres updated to 14.5
=> OCT-451 - Updated postgres version

seed-data-scripts/publication-metadata/script.js, seed-data-scripts/replace-doi-urls/package-lock.json, seed-data-scripts/replace-doi-urls/package.json, seed-data-scripts/replace-doi-urls/script.js
The purpose of this PR was to add the script that has been used to replace DOI urls within the Seed Data txt file to the codebase.
Added the updated files to the [ticket](https://jiscdev.atlassian.net/browse/OCT-440)
---
---
---
=> OCT-440 Add references to seed data

ui/package-lock.json, ui/package.json, ui/src/hooks/index.ts, ui/src/hooks/useMatomoNext.ts, ui/src/pages/_app.tsx
The purpose of this PR was to add matomo tracking code using matomo next
Added required env variables to prod environment on AWS Amplify
---
As per [OCT-231](https://jiscdev.atlassian.net/browse/OCT-231)
---
=> OCT-231 Add matomo tracking code

.github/workflows/api-tests.yml
=> Oct 456 fixes

ui/src/components/Publication/ContentSection/index.tsx, ui/src/pages/publications/[id]/index.tsx
adjust the margins and padding underneath publication author.
keep render at screen width < 1024px consistent
---
---
=> OCT-458 conditionally adjust padding & margin

.github/workflows/api-tests.yml, api/.env.example, api/Dockerfile, api/docker-compose.yml, api/package-lock.json, api/prisma/seed.ts, api/src/components/authorization/service.ts, api/src/components/image/service.ts, api/src/components/reference/controller.ts, api/src/components/user/__tests__/getUserPublications.test.ts, api/src/lib/email.ts, api/src/lib/testUtils.ts, e2e/tests/helpers.ts, ui/next.config.js, ui/package-lock.json, ui/src/components/CommandPalette/index.tsx, ui/src/components/Publication/ContentSection/index.tsx, ui/src/components/SearchToggle/Desktop/index.tsx, ui/src/components/Users/SearchResult/index.tsx, ui/src/lib/api.ts, ui/src/lib/interfaces.ts, ui/src/lib/types.ts, ui/src/pages/browse.tsx, ui/src/pages/index.tsx, ui/src/pages/publications/[id]/index.tsx, ui/src/pages/search/authors/index.tsx, ui/src/pages/search/publications/index.tsx
=> updating int

api/.env.example, api/prisma/migrations/20221216114444_orcid_access_token/migration.sql, api/prisma/schema.prisma, api/serverless.yml, api/src/components/authorization/controller.ts, api/src/components/authorization/routes.ts, api/src/components/authorization/service.ts, api/src/components/user/service.ts, api/src/lib/interface.ts, e2e/playwright.config.ts, e2e/tests/LoggedIn/browse.e2e.spec.ts, e2e/tests/LoggedIn/livePublication.e2e.spec.ts, e2e/tests/LoggedIn/login.e2e.spec.ts, e2e/tests/LoggedIn/profile.e2e.spec.ts, e2e/tests/LoggedIn/publish.e2e.spec.ts, e2e/tests/LoggedIn/search.e2e.spec.ts, e2e/tests/LoggedIn/zRevokeOrcidAccess.spec.ts, e2e/tests/LoggedOut/livePublication.e2e.spec.ts, e2e/tests/LoggedOut/staticPages.e2e.spec.ts, e2e/tests/PageModel.ts, e2e/tests/helpers.ts, ui/src/components/Modal/index.tsx, ui/src/config/endpoints.ts, ui/src/hooks/useAuthCheck.ts, ui/src/lib/api.ts, ui/src/pages/account.tsx, ui/src/pages/faq.tsx
The purpose of this PR was to implement revoking the access to ORCID record from both sides: Octopus and ORCID
---
As per [OCT-372](https://jiscdev.atlassian.net/browse/OCT-372) and [OCT-432](https://jiscdev.atlassian.net/browse/OCT-432)
Fixed all e2e tests and added tests for Revoke ORCID Access from both sites: Octopus and ORCID.
---
[OCT-372]: https://jiscdev.atlassian.net/browse/OCT-372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OCT-372]: https://jiscdev.atlassian.net/browse/OCT-372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OCT-432]: https://jiscdev.atlassian.net/browse/OCT-432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OCT-432]: …
=> OCT-372 + OCT-432 Revoke Permission on Octopus/ORCID

README.md, e2e/tests/LoggedIn/browse.e2e.spec.ts, e2e/tests/LoggedIn/profile.e2e.spec.ts, e2e/tests/LoggedOut/browse.e2e.spec.ts, e2e/tests/PageModel.ts, ui/src/components/Nav/index.tsx, ui/src/pages/authors/[id]/index.tsx
The purpose of this PR was to tidy up my profile/publications pages
---
As per [OCT-495](https://jiscdev.atlassian.net/browse/OCT-495?atlOrigin=eyJpIjoiZDdlNGYwYzgyOTYzNDhjNjgwMTMzN2E3OWQ2MGMxOGQiLCJwIjoiaiJ9)
---
[OCT-495]: https://jiscdev.atlassian.net/browse/OCT-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OCT-495]: https://jiscdev.atlassian.net/browse/OCT-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-495 Tidy up my profile/publications pages

ui/src/components/Publication/Creation/CoAuthorEntry/index.tsx
The purpose of this PR was to update OCT-316 from Tim after it was released on int.
=> OCT-316 - Update - Updated colour of icon to indicate it's pending

api/src/components/coauthor/controller.ts, e2e/tests/LoggedIn/publish.e2e.spec.ts, e2e/tests/PageModel.ts, ui/src/layouts/Error.tsx, ui/src/pages/author-link.tsx
The purpose of this PR was to add error messages to co author denial work flow and update some existing text.
---
As Per [OCT-326](https://jiscdev.atlassian.net/browse/OCT-326?atlOrigin=eyJpIjoiMWViZDJiNTgwYTNiNDRmZWIzYmYwMzliZDViZjRlNzMiLCJwIjoiaiJ9)
---
[OCT-326]: https://jiscdev.atlassian.net/browse/OCT-326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-326 - Update error messaging for deny workflows

api/src/lib/helpers.ts
The purpose of this PR was to fix corresponding author duplication when sending the payload to Datacite
---
---
---
=> OCT-271 Fixed Datacite authors duplication

ui/src/components/Header/index.tsx, ui/src/components/SurveyWidget/index.tsx, ui/src/pages/faq.tsx, ui/src/pages/user-terms.tsx
The purpose of this PR was to fix some text issues
---
As per [OCT-527](https://jiscdev.atlassian.net/browse/OCT-527?atlOrigin=eyJpIjoiYWQwZWU4NWZlNjIzNDM5NDg2YTVhMTc1YTMzODQ5ZDgiLCJwIjoiaiJ9)
[OCT-527]: https://jiscdev.atlassian.net/browse/OCT-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-527 - Simple text fixes

api/src/components/verification/__tests__/confirmCode.test.ts, api/src/lib/email.ts
The purpose of this PR was to fix/improve inconsistent email formatting across email clients
---
As per [OCT-289](https://jiscdev.atlassian.net/browse/OCT-289)
---
---
Mac OS
Gmail (SVGs are not supported... We may discuss this and replace SVG with JPG/PNG)
Outlook web client (can't do much about images since they are wiped out by the email client)
[OCT-289]: https://jiscdev.atlassian.net/browse/OCT-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Temp Mail inbox
=> OCT-289 Inconsistent email formatting

e2e/tests/LoggedIn/publish.e2e.spec.ts, e2e/tests/PageModel.ts, e2e/tests/helpers.ts, ui/src/components/ApprovalsTracker/index.tsx, ui/src/components/Link/index.tsx, ui/src/components/Publication/Visualization/index.tsx, ui/src/lib/interfaces.ts, ui/src/pages/publications/[id]/index.tsx
The purpose of this PR was to provide a way for the **Corresponding author** to **publish** (from the preview publication page) after all the other authors have approved their involvement
---
---
---
=> OCT-526 Publishing after co-author approval is acquired

e2e/tests/LoggedIn/publish.e2e.spec.ts, ui/src/components/Publication/SimpleResult/index.tsx, ui/src/lib/interfaces.ts
The purpose of this PR was to Indicate to authors whether action is needed from their /author page
---
As Per [OCT-529](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-529)
[OCT-529]: https://jiscdev.atlassian.net/browse/OCT-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-529 - Indicate to authors whether action is needed from their /author page

api/prisma/migrations/20230224131225_co_author_reminders/migration.sql, api/prisma/schema.prisma, api/serverless.yml, api/src/components/coauthor/__tests__/createCoAuthor.test.ts, api/src/components/coauthor/__tests__/deleteCoAuthor.test.ts, api/src/components/coauthor/controller.ts, api/src/components/coauthor/routes.ts, api/src/components/coauthor/schema/index.ts, api/src/components/coauthor/schema/sendApprovalReminder.ts, api/src/components/coauthor/schema/updateAll.ts, api/src/components/coauthor/service.ts, api/src/components/publication/service.ts, api/src/lib/email.ts, api/src/lib/interface.ts, e2e/tests/LoggedIn/publish.e2e.spec.ts, e2e/tests/helpers.ts, ui/src/components/ApprovalsTracker/index.tsx, ui/src/layouts/BuildPublication.tsx, ui/src/lib/helpers.tsx, ui/src/lib/interfaces.ts
The purpose of this PR was to provide a way for corresponding authors to send approval reminders to the co-authors
---
As per [OCT-317](https://jiscdev.atlassian.net/browse/OCT-317)
---
Added e2e test for sending reminders flow
---
[OCT-317]: https://jiscdev.atlassian.net/browse/OCT-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-317 Email notifications - Co-Author Reminders

ui/package-lock.json, ui/src/components/Banner/index.tsx, ui/src/components/Header/index.tsx, ui/src/pages/faq.tsx
The purpose of this PR was to remove text from FAQ and Banner
---
As per [OCT-559](https://jiscdev.atlassian.net/browse/OCT-559)
---
---
[OCT-559]: https://jiscdev.atlassian.net/browse/OCT-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-559 Modify copy to avoid pre-launch terminology

ui/src/layouts/BuildPublication.tsx
The purpose of this PR was to fix request approval for older publications that don't have the corresponding author listed.
=> OCT-521 - Fix request approval

api/serverless.yml, infra/modules/s3/main.tf
The purpose of this PR was to update the s3 terraform in order to add a bucket for us to store pdfs with a public read policy.
=> OCT-496-tf - Update Terraform 

infra/modules/s3/main.tf
The purpose of this PR was to keep the tf updated with the working code.
=> OCT-496-TF-Fix - Small fix 

api/src/components/publication/controller.ts, api/src/components/publication/service.ts, api/src/lib/helpers.ts, api/src/lib/interface.ts, ui/src/components/Publication/SidebarCard/Actions/index.tsx
The purpose of this PR was to allow users to preview PDFs for any LIVE publication
---
As per [OCT-584](https://jiscdev.atlassian.net/browse/OCT-584)
---
---
[OCT-584]: https://jiscdev.atlassian.net/browse/OCT-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-584 Creating PDFs for new publications automatically

ui/src/components/Alert/index.tsx, ui/src/components/FileUpload/index.tsx, ui/src/components/URLSourceUpload/index.tsx, ui/src/pages/publications/[id]/index.tsx
The purpose of this PR was to fix reversed modal action buttons.
Fixed Alert component not rendering properly. The background was not updating correctly when changing 'severity' prop
---
---
---
=> OCT-558 Modify ambiguous modal buttons

e2e/tests/LoggedIn/publish.e2e.spec.ts, ui/src/components/Publication/SimpleResult/index.tsx, ui/src/pages/verify.tsx
The purpose of this PR was to update publications statuses shown on My Profile page for authors of a publication
---
---
---
=> OCT-576 Reword "My Profile" statuses

api/src/components/coauthor/controller.ts, api/src/lib/email.ts, e2e/tests/LoggedIn/publish.e2e.spec.ts, e2e/tests/LoggedOut/staticPages.e2e.spec.ts, e2e/tsconfig.json
The purpose of this PR was to notify co-authors if the publication was edited
---
---
---
=> OCT-567 Send new email to confirmed authors when approval is re-requested

infra/create-app/prod.s3.tfbackend, ui/src/pages/about.tsx
The purpose of this PR was fix the broken video, however the video was outdated and contained a logo we no longer use, so discussed with PO and decided  to remove the video section for the moment. 
---
As Per [OCT-549](https://jiscdev.atlassian.net/browse/OCT-549?atlOrigin=eyJpIjoiYTIzMTM0MGNiMTkxNGQxZWE2NWJjZDM4Mzc3NTYwMTAiLCJwIjoiaiJ9)
[OCT-549]: https://jiscdev.atlassian.net/browse/OCT-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-549 - Video on about page not loading

ui/src/components/Publication/Creation/Review.tsx
The purpose of this PR was to update Review & publish section on the edit draft page.
Also reordered sections based on their order in the sidebar
---
As per [OCT-571](https://jiscdev.atlassian.net/browse/OCT-571)
---
---
[OCT-571]: https://jiscdev.atlassian.net/browse/OCT-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-571 Rename "Full Text" to "Main Text" in completeness checker

api/src/components/coauthor/controller.ts
The purpose of this PR was to fix a bug regarding publication remaining LOCKED after all co-authors denied their involvement and they were removed from publication. 
The corresponding author had no way to edit that publication anymore.
---
---
---
=> FIXED BUG - publication is still LOCKED after all co-authors denied involvement

README.md, e2e/README.md
The purpose of this PR was to add a README.md to the e2e folder so future developers understand how the tests work and what they are.
=> Added README.md to e2e folder.

.github/PULL_REQUEST_TEMPLATE.md
The purpose of this PR is to update the Github PR template to prompt developers to complete the following 3 actions when they're finishing a PR:
- Test manually locally 
- Update automated tests 
- Update documentation (eg. read me's/ confluence etc) 
---
As per[ OCT-657](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-657)
---
=> Update Github PR Template 

.github/workflows/api-tests.yml, api/docker-compose.yml, api/serverless.yml, api/src/components/user/__tests__/getUserList.test.ts, api/src/components/user/controller.ts, api/src/components/user/routes.ts, api/src/components/user/service.ts, api/src/lib/interface.ts
The purpose of this PR was to create a new endpoint protected by an API KEY which returns the list of Octopus users for mailings
---
As per [OCT-621](https://jiscdev.atlassian.net/browse/OCT-621)
---
---
[OCT-621]: https://jiscdev.atlassian.net/browse/OCT-621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-621 Endpoint to provide a list of user emails

api/serverless.yml
The purpose of this PR was to add the queue url to the parameter store.
=> OCT-614  Serverless changes

api/package-lock.json, api/package.json
The purpose of this PR was to remove ts-node from the project dependencies.
---
As Per [OCT-664](https://jiscdev.atlassian.net/browse/OCT-664?atlOrigin=eyJpIjoiNDU0MWY5MTRlN2I0NDA5Mjk2NTExOTljYjFlNWI0ZDMiLCJwIjoiaiJ9)
---
[OCT-664]: https://jiscdev.atlassian.net/browse/OCT-664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-664 - Remove ts-node from package.json - Red Dependency

e2e/package-lock.json, e2e/package.json, e2e/tests/LoggedIn/publish.e2e.spec.ts
The purpose of this PR was to update e2e dependencies
---
As per [OCT-647](https://jiscdev.atlassian.net/browse/OCT-647)
---
---
---
[OCT-647]: https://jiscdev.atlassian.net/browse/OCT-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-647 update e2e dependencies

ui/src/components/ApprovalsTracker/index.tsx
The purpose of this PR was to bring back code which has been removed by accident while resolving conflicts
---
As per [OCT-668](https://jiscdev.atlassian.net/browse/OCT-668)
---
---
---
BEFORE
AFTER
[OCT-668]: https://jiscdev.atlassian.net/browse/OCT-668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-668 Display affiliations in the acceptance tracker component vertically

api/package-lock.json, api/package.json
The purpose of this PR was to fix **semver** security vulnerabilities raised by Snyk in code report.
It seems that we don't use @serverless/utils in our project, I have removed it completely.
---
---
---
---
=> OCT-715 investigate semver fix for serverless

api/package-lock.json, api/package.json
The purpose of this PR was to remove crypto-random-string from api/package.json which has been forgotten during upgrades. This package has been replaced with a custom helper function which generates OTPs
---
---
---
---
=> API - Removed forgotten crypto-random-string package

api/nodemon.json, api/package-lock.json, api/prisma/seeds/publications.ts, api/serverless.yml, api/src/components/publication/__tests__/getResearchTopics.test.ts, api/src/components/publication/controller.ts, api/src/components/publication/routes.ts, api/src/components/publication/service.ts
The purpose of this PR was to create a custom endpoint that will be used to retrieve the list of all research problems that need to be converted to research topics
---
---
---
---
=> OCT-716 Create endpoint to get the list of all research problems which are topics

api/package-lock.json, api/package.json, api/prisma/convertResearchTopics.ts, api/src/components/publication/service.ts, api/src/lib/interface.ts
The purpose of this PR was to convert research problems (classified as topics) to research topics.
At this stage we're not deleting any of the research problems which are converted to topics, we're only creating topics and relationships between them and research problems.
God problem will also be converted to a god topic so that high level topics can be linked to it.
---
As per [OCT-600](https://jiscdev.atlassian.net/browse/OCT-600)
---
---
---
[OCT-600]: https://jiscdev.atlassian.net/browse/OCT-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-600 Converting the LOC classification outline to Research Topics

api/serverless.yml, api/src/components/topic/__tests__/getTopics.test.ts, api/src/components/topic/controller.ts, api/src/components/topic/routes.ts, api/src/components/topic/schema/getTopics.ts, api/src/components/topic/schema/index.ts, api/src/components/topic/service.ts, api/src/lib/interface.ts, e2e/tests/LoggedOut/search.e2e.spec.ts, ui/src/components/ScrollToTop/index.tsx, ui/src/components/Users/SearchResult/index.tsx, ui/src/layouts/BuildPublication.tsx, ui/src/lib/helpers.tsx, ui/src/lib/interfaces.ts, ui/src/lib/types.ts, ui/src/pages/search/authors/index.tsx, ui/src/pages/search/publications/index.tsx, ui/src/pages/search/topics/index.tsx
The purpose of this PR was to create a new search page for topics similar to the existing /search/publications and /search/authors
---
As per [OCT-622](https://jiscdev.atlassian.net/browse/OCT-622)
---
---
---
[OCT-622]: https://jiscdev.atlassian.net/browse/OCT-622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-622 Research topic search

api/package-lock.json, api/package.json, api/prisma/removeResearchTopicProblems.ts, api/src/components/publication/service.ts
The purpose of this PR was to create a script which will remove all research problems that have been converted to research topics beside the ones which have Hypothesis children attached (if any) including god problem.
---
As per [OCT-711](https://jiscdev.atlassian.net/browse/OCT-711)
---
---
---
[OCT-711]: https://jiscdev.atlassian.net/browse/OCT-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OCT-711 Remove problems with associated topics

amplify.yml
The purpose of this PR was to store our AWS amplify build config in version control because up until now it was only in the AWS console.
---
None
---
---
---
=> Add amplify.yml to repo

ui/src/components/Nav/index.tsx, ui/src/config/urls.ts
The purpose of this PR was to re-organise nav links
---
As per [OC-695](https://jiscdev.atlassian.net/browse/OC-695)
---
---
---
[OC-695]: https://jiscdev.atlassian.net/browse/OC-695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OC-695 "About" and "How To" in nav bar

api/src/lib/helpers.ts
The purpose of this PR was to show which affiliations each author has in a publication PDF.
---
1. Each affiliation is displayed in a numbered, de-duplicated list
2. Each author has a superscript number corresponding to each affiliation they have entered
---
---
API:
E2E:
---
=> OC-694: Split PDF affiliations by author

ui/src/components/BlogCard/index.tsx, ui/src/lib/types.ts, ui/src/pages/blog/[slug].tsx, ui/src/pages/blog/index.tsx
The purpose of this PR was to add a custom date field to the blogs page and sort blogs by it.
---
As per [OC-691](https://jiscdev.atlassian.net/browse/OC-691)
---
---
---
[OC-691]: https://jiscdev.atlassian.net/browse/OC-691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OC-691 Adding a custom date field for Octopus' blog

ui/src/components/Nav/Desktop/index.tsx
The purpose of this PR was to fix navigation links flicker while hovered.
---
As per [OC-709](https://jiscdev.atlassian.net/browse/OC-709)
---
---
---
[OC-709]: https://jiscdev.atlassian.net/browse/OC-709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OC-709 Flicker when moving cursor away from dropdown items

api/Dockerfile, ui/src/components/Nav/index.tsx, ui/src/pages/research-culture-report.tsx
The purpose of this PR was to create a new page called: Research Culture Report.
The page content was provided into the ticket description.
---
As per [OC-696](https://jiscdev.atlassian.net/browse/OC-696)
---
---
---
[OC-696]: https://jiscdev.atlassian.net/browse/OC-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OC-696 Dedicated page for hosting research culture report

api/prisma/migrations/20231211094223_event_type_enum/migration.sql
The purpose of this PR was to add db migration for event type column change
---
---
---
---
=> OC-387 Transferring corresponding authorship - DB migration

ui/src/pages/about.tsx, ui/src/pages/get-involved.tsx, ui/src/pages/index.tsx, ui/src/pages/user-terms.tsx
This reverts the changes made in PR #628 - we don't want to put these changes out without corrections which will be done later.
=> Revert homepage changes

infra/modules/s3/pdf-processing-lambda-src/index.js
The purpose of this PR was to add a prefix to the publication type we output in metadata sent to publication router, because at the moment Eprints detects "thesis" in "HYPOTHESIS".
---
- Notifications sent to publications router include “Octopus article; “ in the publication type field before the publication type. For instance “Octopus article; METHOD”
---
---
Metadata logged when the function was run on int environment.
=> OC-849: "Octopus article" publication type

.github/workflows/api-tests.yml, api/package-lock.json, api/package.json, e2e/tests/LoggedIn/publish.e2e.spec.ts, ui/package-lock.json, ui/package.json
The purpose of this PR was to fix a security issue in the version of the axios package we are using in the UI and API. This was fixed in version 1.7.4.
---
Axios is installed at version 1.7.4 in the UI and API projects.
---
---
E2E
API
UI
=> OC-903: Update axios to 1.7.4

infra/modules/s3/pdf-processing-lambda-src/index.js
The purpose of this PR was to go live with pubrouter. All this involves is changing the URL we hit on the prod environment from the UAT one to the live one.
This has been applied already.
---
- Calls made from prod are sent to pubrouter.ac.uk instead of uat.pubrouter.ac.uk
---
=> OC-995: Pubrouter golive

api/package-lock.json, api/package.json, api/src/components/event/__tests__/processRequestControlEvents.test.ts
The purpose of this PR was to fix a symlink attack vulnerability in the tar-fs package depended on by @sparticuz/chromium and puppeteer-core.
---
- @sparticuz/chromium is installed at a minimum of 132.0.0.
- puppeteer-core is installed at a minimum of 24.2.0
---
---
API
E2E
=> OC-1040: Fix Symlink Attack

api/package-lock.json, api/package.json, ui/package-lock.json, ui/package.json
The purpose of this PR was to fix an SSRF vulnerability in axios.
---
- The API and UI are using >= v1.8.3 of axios.
---
---
API
UI
E2E
=> OC-1039: Fix Server-side Request Forgery (SSRF)

api/src/components/integration/ariUtils.ts, api/src/components/integration/service.ts
The purpose of this PR was to fix an issue I noticed in my code for #814, where the call to trigger the ECS task relied on the dryRun parameter being set. Here I have corrected it to work correctly either way the parameter is set.
=> OC-1066 fix: Fix ECS call

ui/package-lock.json
The purpose of this PR was to fix a high vulnerability: https://security.snyk.io/vuln/SNYK-JS-LINKIFYJS-11502189
---
- The TipTap editor is not affected
---
=> OC-1116: SNYK-JS-LINKIFYJS-11502189

.github/workflows/ui-tasks.yml
=> GEM-21 update ui-tasks.yml
