JiscSD/octopus

api/src/components/authorization/controller.ts
ui/src/pages/publications/[id]/index.tsx

The purpose of this PR was to fix the issue that was causing certain users to not be able to login. This was caused by possible null values for `{ day: null }`.
This was fixed with more optional chaining.
Also fixed the issue where certain publications were not displaying. This was an easy fix, i needed to display if either `linkedTo` or `linkedFrom` have length, previously I was only checking `linkedTo`.

Fix issue where ORCID login was not working because of null values

---

api/src/components/user/service.ts
ui/src/components/Avatar/index.tsx
ui/src/components/Users/HistoryTable/index.tsx
ui/src/components/Users/SearchResult/index.tsx
ui/src/components/index.tsx
ui/src/lib/interfaces.ts
ui/src/pages/authors/[id]/index.tsx
ui/src/pages/search.tsx

The purpose of this PR was display an orcid users education & employment history on their public profile page.
[For Jira ticket: 184](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-184)
---
Now that the api / database is storing user data from orcid on the users employment & educational history. This information needs to be displayed on the users (authors) public page.
- If author has employment history from orcid, it should be made visible on their author page
- If author has education history from oricd, it should be made visible on their author page
---
---
https://user-images.githubusercontent.com/81176162/158167581-cca02a20-428c-42e2-b279-5a0ea5009dc7.mov

Added employment & education history to public profile

---

ui/src/lib/api.ts
ui/src/lib/types.ts
ui/src/pages/search.tsx

The purpose of this PR was to update the UI so that the search filtering options better align with the octopus api as the search functionality has been updated to use OpenSearch. 
[For jira ticket 185](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-185)
---
User should only be able to order publications results by title or published date

Updated search result page filtering to align with api (oct-185)

---

api/src/components/publication/schema/getAll.ts
api/src/components/publication/service.ts
api/src/lib/interface.ts

The purpose of this PR was to modify the `GET /publications` to include an `exclude` query parameter.
> GET /publications?exclude=id1,id2
This endpoint is primarily used for finding a list of "linkable" publications. We will pass in a comma seperated list of ids that should not be returned from the DB.

Exclude ids from GET /publications

---

api/prisma/migrations/20220412125234_init/migration.sql
api/prisma/schema.prisma
api/prisma/seeds/publications.ts
api/prisma/seeds/users.ts
api/serverless.yml
api/src/components/publication/__tests__/createFlag.test.ts
api/src/components/publication/__tests__/createFlagComment.test.ts
api/src/components/publication/__tests__/resolveFlag.test.ts
api/src/components/publication/controller.ts
api/src/components/publication/routes.ts
api/src/components/publication/schema/createFlag.ts
api/src/components/publication/schema/createFlagComment.ts
api/src/components/publication/schema/index.ts
api/src/components/publication/service.ts
api/src/components/user/__tests__/getUser.test.ts
api/src/lib/interface.ts
api/src/lib/testUtils.ts

The purpose of this PR was to create an API endpoints for a flagging dispute process so that users can comment on and resolve flags. We also resolved a bug on the `createFlag` endpoint.
Once a flag is created, this opens up the ability to add “comments” to that chain, where both the “flagger” and publication owner can leave comments. Once the “flagger” is satisfied that this red flag has been resolved, they can mark the conversation as resolved. This will effectively hide the flag and resolve it on the database. 
Only the ‘flagger’ or author of the flagged publication have the ability to comment, and only the flagger or a super user has the ability to resolve the flag.  
We have created two different end points, **one to add comments to a flagged publication:**
Path: `POST …

Create an API endpoint for a flagging dispute process

---

.gitignore
api/package-lock.json
api/package.json
api/prisma/migrations/20220419100253_images/migration.sql
api/prisma/schema.prisma
api/prisma/seed.ts
api/serverless.yml
api/src/components/coauthor/controller.ts
api/src/components/coauthor/routes.ts
api/src/components/image/controller.ts
api/src/components/image/routes.ts
api/src/components/image/service.ts
api/src/lib/interface.ts
api/tsconfig.json
docker-compose.yml
infra/create-app/main.tf
infra/modules/s3/main.tf
infra/modules/s3/vars.tf
ui/src/lib/helpers.tsx
ui/src/pages/index.tsx

The purpose of this PR was to create the ability to upload and delete images via the API. A lot went into this PR:
- Updated Terraform to include an `s3` module, that will create the `s3` bucket needed to store images per environment (i.e `int`, `prod`, etc).
- Updated `docker-compose` to add `localstack`, enabling us to run a copy of `s3` locally.
- Updated seed command so that it checks if a local `s3` bucket exists, if it doesn't, it will create, `science-octopus-publishing-images-local`.
- Added `image` model to prisma. This does not store the image, only a reference to it (i.e `id`, `name`, `user` and `createdAt`).
- Added helper function to UI, to get Base64 of image.
> POST /images
```json
{
"name": "my-first-image",
"image": …
```

Adding/deleting images via the API (OCT-196)

---

api/src/components/publication/schema/getAll.ts
api/src/components/publication/service.ts
api/src/lib/interface.ts
ui/package.json
ui/src/pages/search.tsx

The purpose of this PR was to add an optional dates range to the search filters for the get all publications endpoint. 
This PR contains amendments to the `getAllPublications` endpoint, search filters and changes to the UI to display the date input fields which is functional. 
Will need further styling with a date picker or similar.

Add dates range to search filters on the Get Publications API endpoint

---

api/serverless.yml
infra/.gitignore
infra/create-app/int.tfvars
infra/modules/s3/main.tf
ui/src/config/urls.ts

**Infra changes**
- Added tfvar files to the repository (we never use these to store sensitive values, and committing these would go against best practice anyway).
- Added `int.tfvars` file
- Set iam policy for s3 public access
**API changes**
Added `iamRoleStatement` (at request of @nathan-at-jisc) for lambda and email functions.
**UI changes**
Fixed the s3 bucket url for user uploaded content (eg. publication editor)
Currently object src are along the lines of...
https://science-octopus-publishing-images-int.eu-west-1.amazonaws.com//cl2yizbzd000009mr0dr62uhv
Where they need to be:
https://science-octopus-publishing-images-int.s3.eu-west-1.amazonaws.com/cl2yizbzd000009mr0dr62uhv 
This fix removes the surplus slash, and adds `s3` to the bucket url.
---
n/a
---
No additional
---
n/a

Update mediaBucket values

---

ui/src/pages/create.tsx

The purpose of this PR was to allow the publication creation page to accept two query params. 
1. A publication type, if available, the dropdown of publication type is pre selected & disabled disallowing change.
2. A publication for ID. If provided, on creation of the publication, an attempt of creating a link will be done.
[For Jira Ticket 197](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-197)
---
A user can select to write a review of a publication. This will take them to the publication creation page with information pre selected. The link to that publication for review will automatically be created.
---
https://user-images.githubusercontent.com/81176162/167603247-53905e5b-2b2b-4c3d-943a-87a8bc5d9832.mov

Create peer review from publication page (query params) OCT-197

---

ui/src/pages/search.tsx

The purpose of this PR was to show a date picker on search filter input fields `date from` and `date to`.
---
This extends from the existing [OCT-210](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-210) ticket.
---
No additional tests. Manual testing carried out:
https://user-images.githubusercontent.com/86601264/169331622-07a50e09-de6a-4039-ba48-58e7790e81e8.mov
---

OCT-210 Date filter input type for date picker

---

ui/src/pages/verify.tsx

The purpose of this PR was to add explanatory copy to the verify email page.
---
Copy should read:
> A verified email is required for essential service notifications. We’ll use it as described in our privacy notice (at https://int.octopus.ac/privacy) only to provide the Octopus service. We’ll store your email address until we are told that you no longer wish to hold an account. You can update your email address at any time from your user account page.
---
No additional.
---

OCT-209 Updated copy for verify email page

---

api/prisma/migrations/20220524111833_init/migration.sql
api/prisma/schema.prisma
api/src/components/publication/schema/create.ts
api/src/components/publication/schema/update.ts
api/src/components/publication/service.ts
api/src/lib/interface.ts
ui/src/components/Button/index.tsx
ui/src/components/Publication/Creation/Funders.tsx
ui/src/components/Publication/Creation/StepTwo.tsx
ui/src/layouts/BuildPublication.tsx
ui/src/lib/helpers.tsx
ui/src/lib/interfaces.ts
ui/src/lib/types.ts
ui/src/pages/publications/[id]/edit.tsx
ui/src/pages/publications/[id]/index.tsx
ui/src/stores/publicationCreation.ts

The purpose of this PR is to create a feature that enables users to add optional details regarding the funders of their publication. 
This PR contains amendments to the API, changes to the `Publication` schema to store the funder's statement, the addition of the free text fields on the UI and the displaying of the statement (if specified) on the Publication page. It also contains amendments to the 'funders' page within the build publication process as per Lola's request, including: regulation on the 'link' field to check that the user has given a valid URL, copy tweaks, a button that links to [https://ror.org/](url) and styling tweaks.
- The free text field should only display if the user has added funders to the publication - this is the same for the UI on the publication page
- The free …

Create a 'funders statement' free text field - API & UI

---

ui/src/pages/search.tsx

Hides the date pickers on the `/search` page when the chosen search type is 'users'. This fixes a bug where a runtime error would occur as a date filter is only valid for publications.
I also spotted the empty results alert contained placeholder text so have populated that with some more useful text.
Issue: #151 
---
Go to the search page and change the search type to users, the date pickers should disappear. Changing back to publications should make them reappear again.

OCT-issue-151

---

ui/src/components/Footer/index.tsx
ui/src/components/Header/index.tsx
ui/src/pages/_app.tsx
ui/src/pages/about.tsx
ui/src/pages/index.tsx
ui/src/pages/login.tsx

The purpose of this PR is to redirect to the about page until the ORCID login (and other things) gets fixed. This PR needs to get revisited once these things get sorted.
Only the following pages can be navigated to:
```
'/about',
'/faq',
'/privacy',
'/terms',
'/accessibility',
'/author-guide',
'/octopus-aims',
'/get-involved'
```
---
[Enable links](https://github.com/JiscSD/octopus/blob/main/ui/src/components/Footer/index.tsx)
[Enable links](https://github.com/JiscSD/octopus/blob/main/ui/src/components/Header/index.tsx)
[Remove redirects](https://github.com/JiscSD/octopus/blob/main/ui/src/pages/_app.tsx)
[Remove redirects](https://github.com/JiscSD/octopus/blob/main/ui/src/pages/index.tsx)
[Enable page section](https://github.com/JiscSD/octopus/blob/main/ui/src/pages/about.tsx)
--- …

OCT-225 Holding page - Use modified about page as homepage

---

ui/src/pages/verify.tsx

This PR addresses issue #169 / [OCT-236](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-236).
This bug surrounds emails being sent to newly verified users. To reproduce:
1. Log in as new user
2. Verify email
3. Raise red flag on a publication
The flag will be raised, and the author of the publication will receive a _“Your publication has been red flagged”_ email, but the newly verified user does not receive the _“Red flag created”_ email.
On logging out, and back in, creating a red flag, emails work as expected.
This turned out to be an incorrect use of `user?.token` within setUser. This resulted in a `null` value being set instead of the new, verified email address which was available in `getToken.data.token`
---
Should resolve issue as raised.
--- …

OCT-236 Token issue following email verification

---

ui/src/components/Nav/Desktop/index.tsx

The purpose of this PR was to resolve a [minor bug fix](https://github.com/JiscSD/octopus/issues/183) within the ui. The headers which contain the publication types within the 'linked publication visualisation' overlap the dropdown profile menu when the user is accessing the page from a desktop browser. 
This PR contains changes to the z index of the dropdown menu within the nav bar.

Overlapping issue with the dropdown profile menu and the linked publication visualisation section - UI

---

ui/src/components/Publication/Creation/CoAuthor.tsx
ui/src/pages/create.tsx
ui/src/pages/publications/[id]/edit.tsx

The purpose of this PR was to add a link to the author guide on the 'create a publication' page, to change the position of the co-author step within the publication build process and to add some copy to the co-author page. Because both tickets are quite small, I've done both tickets ([OCT-237](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-237) and [OCT-241](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-241)) in this PR. 
Acceptance Criteria: 
- Move coauthor to final stage of the publication form. 
- Add the following copy to the co-author page in the publication form:
```
Add the email addresses of any co-authors involved in this publication. Note that they will immediately receive an email asking them to …
```

Add link to author guide on create publication page and change position of the 'Co-author' step within the publication build process

---

ui/src/components/RORForm/index.tsx
ui/src/pages/create.tsx
ui/src/pages/publications/[id]/index.tsx

The purpose of this PR was to remove the 'Affiliated Organisations' and 'Funders' limit which only shows free text field when organisation has been added (within the publication creation process). Initially you could only add a statement if you had added at least one organisation, but now you can at a statement regardless. This PR contains amendments to the ROR form and amendments to the publication index page with the UI.
---

Allow users to add an 'Affiliated Organisations' and/or 'Funders' statement if no organisation has been added - UI

---

api/prisma/migrations/20220706145818_update_ethical_statement/migration.sql
api/prisma/schema.prisma
api/prisma/seeds/publications.ts
api/src/components/publication/schema/create.ts
api/src/components/publication/schema/update.ts
api/src/lib/interface.ts
ui/src/components/Publication/Creation/DataStatements.tsx
ui/src/components/Publication/Creation/Review.tsx
ui/src/components/Publication/SearchResult/index.tsx
ui/src/lib/interfaces.ts
ui/src/lib/types.ts
ui/src/pages/publications/[id]/index.tsx
ui/src/pages/search.tsx

The purpose of this PR was to fix a bug in the ethical statement section of the publication flow.
JIRA Ticket: https://jiscdev.atlassian.net/browse/OCT-247
Ethical statement doesn't count as completed if second option is selected
This is only for ‘Results’ types.
Incorrect functionality at the moment:
- When choosing the second option, the ‘ethical statement’ section is shown as not complete.
- The optional free text field is shown with both options, it should only be shown when the first option is selected.
I have also:
- Implemented accessibility fixes so that lighthouse ci passes
- Added in a missing doi to the test seed data so that api tests can be run locally
---
A user wants to publish a 'Results' publication and the results involved human or animal subjects, then: they tick 'The …

OCT-247 - Ethical Statement blocking publication

---

ui/src/components/Publication/Creation/DataStatements.tsx
ui/src/components/Publication/Creation/LinkedPublications.tsx
ui/src/components/Publication/Creation/Review.tsx
ui/src/config/values.ts
ui/src/layouts/BuildPublication.tsx
ui/src/pages/about.tsx
ui/src/pages/index.tsx
ui/src/stores/publicationCreation.ts

The purpose of this PR was to fix a bug in the data permissions section of the publication flow.
JIRA Ticket: https://jiscdev.atlassian.net/browse/OCT-240
The mandatory free text field is appearing with both options but should only show when option 1 is chosen, so it is blocking the publication flow. 
I have also changed the logic so that the 'Data permissions statement provided by' section on the review page only shows when option 1 has been selected for data permissions, and corrected a few typos.
This is only for ‘Results’ types. 
Incorrect functionality at the moment:
- On the ‘review and publish’ the section ‘Data permissions statement provided by' is shown even when the second option for ‘Data permissions’ is selected so the free text field is not needed to continue with the …

OCT-240 Data permissions statement blocking publication

---

ui/src/components/Banner/index.tsx
ui/src/components/Footer/index.tsx
ui/src/components/Header/index.tsx

The purpose of this PR was to make the help & feedback links more prominent across the website. 
- Update site banner to read:
This is a beta release under active development. Help us improve by providing [feedback ](https://forms.office.com/pages/responsepage.aspx?id=TTn5SBSKJ02CpvNfEjYSBdQdk25FM49NmnYND3Z_nExUNE5TNzVQNTdXNTY0UFdOT05CNkZUVDBZSy4u)or contacting [help@jisc.ac.uk](mailto:help@jisc.ac.uk) With 'feedback' linking to https://forms.office.com/pages/responsepage.aspx?id=TTn5SBSKJ02CpvNfEjYSBdQdk25FM49NmnYND3Z_nExUNE5TNzVQNTdXNTY0UFdOT05CNkZUVDBZSy4u 
- Make helpdesk email more prominent - e.g. move higher in footer or add mail icon alongside social ones.

Amendments to banner & footer to make the help email more prominent - UI (OCT-

---

ui/lighthouserc.js
ui/src/config/urls.ts
ui/src/pages/accessibility.tsx
ui/src/pages/faq.tsx
ui/src/pages/user-terms.tsx

Summary:
There are some links in prod still pointing to int. These need to be updated.
Links in pages should simply be absolute paths (without the domain name)
Acceptance Criteria:
Publication flow
Linked publications – in the explanatory text theres a link for each publication type to the int/about, needs to link to [Octopus](https://prod.octopus.ac/faq#pub_type_octopus)  - **DONE IN OCT-254**
FAQS: [Octopus](https://prod.octopus.ac/faq) 
Int link under Is everything on Octopus open access? (also change to new terms page)
Terms: [Octopus](https://prod.octopus.ac/user-terms) 
Section 1, 12
Footer
Terms link needs to point to [Octopus](https://prod.octopus.ac/user-terms) 
Github:
Point to live URL. - **NOT DONE**

OCT-253 fix hard coded links to int.octopus.ac

---

ui/src/config/urls.ts
ui/src/pages/publications/[id]/edit.tsx

The purpose of this PR was to fix a bug with how the `affiliations` data is initially propagated within the form. When an author saves their draft, the `affiliations` data is sent to the DB, but when they return to their draft to edit it, the `affiliations` data isn't propagated in the form. I have fixed this by making sure that the affiliations data is pulled in alongside all of the other publication data from the DB and put into store when the publication is initially loaded in.

Fix affiliations bug - UI

---

api/src/components/publication/__tests__/updatePublication.test.ts
api/src/components/publication/controller.ts
api/src/lib/helpers.ts

The purpose of this PR was to fix the 404 errors described in [OCT-260](https://jiscdev.atlassian.net/browse/OCT-260).
1. Publication main body HTML is now sanitised rather than rejected.
2. If a failure does occur, a 500 server error is returned.
---
1. Publication main body HTML should be sanitised rather than rejected.
2. If a failure does occur, a more sensible error code should be returned.
---
- Updated unit tests to reflect sanitised rather than rejected output.
- Manually tested using supplied Word document that was previously rejected.

OCT-260 404 errors on publication creation

---

api/prisma/migrations/20220720091606_conflict_of_interest_bug_fix/migration.sql
api/prisma/schema.prisma
ui/src/components/Publication/Creation/ConflictOfInterest.tsx
ui/src/components/Publication/Creation/Review.tsx
ui/src/config/urls.ts
ui/src/layouts/BuildPublication.tsx
ui/src/lib/interfaces.ts
ui/src/lib/types.ts
ui/src/pages/publications/[id]/edit.tsx
ui/src/stores/publicationCreation.ts

The purpose of this PR was to fix undesired behaviour where the confilict of interest value isn't being retained when a user selects 'no', saves the draft and then returns to the publication, as per this [Jira ticket.](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-263)
It was set up so that the `conflictOfInterestStatus` was either `true` or `false`, `false` by default on the backend and `true` on the UI. This was then overriding the value on the database if the user has selected `false`, so although the data was being retained the UI wasn't giving any feedback that this is the case. 
I have changed it so that the `conflictOfInterestStatus` now accepts three values: undefined, false and true. If a user hasn't selected any value, both radio fields …

Conflict of interest - 'No' value consistently not being retained - BUG - (OCT-263)

---

ui/src/components/Publication/Creation/DataStatements.tsx
ui/src/lib/types.ts

The purpose of this PR was to fix a bug where if a user selects the 'other' the data isn't retained, along with any text the user inputs in the text field, as per this [Jira ticket.](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-303)
This was being caused because the text field is being initialised locally as `''` and isn't referencing the global state, so although the data was being retained on the backend, the UI within the build process was giving no feedback that this was the case. I have now amended it so that once the page mounts, we check to see if the dataAccessStatement matches any of the other statements, if not the `other` field is selected and the free text field is populated with the `dataAccessStatement`.

Data access - 'other' field not being retained - BUG - (OCT-264)

---

ui/src/lib/types.ts
ui/src/pages/author-link.tsx

The purpose of this PR was to improve the error handling for coauthor linking. API error messages and status codes are now shown in the UI.
---
To ensure that a user can understand what error happened when trying to link themselves as a coauthor.
---
Tested manually for these errors:
- 'This publication does not exist.'  
- 'This publication is LIVE and therefore cannot be edited.'  
- 'To link yourself as a co-author, you must be logged in.' Should always redirect  
- 'To link yourself as a co-author, you must have a verified email address.' Should always redirect  
- 'You cannot link yourself as the co-author, if you are the creator.'  
- 'You are already linked as another co-author'  
- 'Email not found as a co-author.' 
- 'User has already been linked to this publication.'
---

OCT-262 - improve error handling for coauthor linking

---

ui/src/lib/types.ts
ui/src/pages/publications/[id]/index.tsx

The purpose of this PR was to fix a broken co author link on the 'view a publication' page. The link was using the user's ORCHID id in the path params for the URL, instead of the `linkedUser` id. I have now amended it so it uses the `linkedUser` id.

Broken co-author link - (OCT-295) - BUG

---

ui/src/layouts/Publication.tsx
ui/src/pages/publications/[id]/index.tsx

The purpose of this PR was to change the current breakpoint for Publication page so that SidebarCard component would be visible on smaller screens. Changed from 1280px to 1024px.
---
As per [OCT-332](https://jiscdev.atlassian.net/browse/OCT-332)
---
BEFORE
AFTER

OCT-332 Change column-width breakpoint for smaller screens

---

ui/src/components/Publication/SidebarCard/Actions/index.tsx

The purpose of this PR was to fix undesired behaviour on the [OCT-200 feature ](https://github.com/JiscSD/octopus/pull/220) where the 'Write a linked [relavent publication type]' buttons don't display when a user is accessing their own publication.
I have now amended it so the buttons display on every publication page, provided the user is logged in and has verified their email address.

Fix OCT-200 bug where the linked publication buttons aren't displaying when a user views their own publication

---

ui/public/robots.txt
ui/src/pages/_app.tsx
ui/src/pages/search.tsx

The purpose of this PR was to remove the noindex meta tag for relevant pages, in order to allow crawlers to index the site
As per [OCT-232](https://jiscdev.atlassian.net/browse/OCT-232)
---
BEFORE
AFTER

OCT-232[partial] Make site indexable

---

ui/src/components/Link/index.tsx
ui/src/components/Publication/ContentSection/index.tsx
ui/src/components/Publication/Creation/MainText.tsx
ui/src/components/Publication/SidebarCard/Actions/Button.tsx
ui/src/layouts/BuildPublication.tsx
ui/src/pages/publications/[id]/index.tsx

The purpose of this PR was to display the new references on the publication page.
As per [OCT-359](https://jiscdev.atlassian.net/browse/OCT-359)
---
BEFORE
AFTER

OCT-359 Output display - live and draft publications 

---

ui/src/components/Publication/SidebarCard/Actions/index.tsx

The purpose of this PR was to fix a bug where an error page is being displayed when a user tries to publish a 'Peer Review' publication, as per this [Jira Ticket](https://jiscdev.atlassian.net/browse/OCT-377). 
This error was due to there being no `PEER_REVIEW` key in the `Helpers.LinkedPublication` object, as well as there being no check to see if the publication is a Peer Review before rendering the linked publication button.

Unable to publish or preview publications of type "Peer Review" - OCT-377 (BUG)

---

ui/src/components/Publication/Creation/MainText.tsx

The purpose of this PR was to add a modal to confirm that the user wishes to delete a reference and inform them of the consequences in doing so. 
---
- ‘Delete reference’ button available on all reference lines. 
- Opens a confirmation, in modal view : Deleting a reference may affect the accuracy of your reference numbering and in-text references. Are you sure you want to delete this reference? This action cannot be undone. 
- User must confirm Delete or Cancel to close the modal and complete the action. 
- The table updates to remove the reference line. 
- Only one reference can be deleted at a time using this button (see delete all ticket for mass deletion feature).
---

OCT-356 Delete reference (single)

---

ui/src/lib/helpers.tsx

The purpose of this PR was to add a secure flag to the `production-octopus-token` cookie to resolve the issue raised in the pen testing report.
---
- Cookie ` production-octopus-token` has the secure flag set to: `true`
---

OCT-338 Pen test: Session Cookie Without Secure Flag

---

api/src/components/authorization/controller.ts

The purpose of this PR was to fix an issue where we ran the .find function on a null field, this now only runs if something is there, otherwise returns null when there are no external ids. 
---
- Bug is fixed
- User with the specified ORCID is able to login.
---
Detailed steps to reproduce:
Only user can reproduce, using ORCID 0000-0002-4299-8978, it should be possible to temporarily swap the code that fetches the user information to use that ORCID instead of the logged in user’s.
---

OCT-378 User cannot login if ORCID profile returns nulls for optional fields

---

api/src/components/user/service.ts
api/src/lib/helpers.ts
ui/src/components/CommandPalette/index.tsx
ui/src/pages/search.tsx

The purpose of this PR was to fix a bug where when the user uses special characters in their search query it breaks the page and returns a 422 error, as per this [Jira ticket](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-405). 
This is because the query isn't encoded. I have used `encodeURIComponent()`  to encode the characters but this needs decoding on the backend so the API can interpret the search query.

OCT-405 '& ' breaks search

---

ui/src/pages/login.tsx
ui/src/pages/verify.tsx

The purpose of this PR was to add conditional rendering for the new text added so that only the users without a verified email will see the updated text: "Your Octopus account has been created..."
---
As per [OCT-373](https://jiscdev.atlassian.net/browse/OCT-373)
---

OCT-373 Email verification page shown after account setup (UPDATE)

---

ui/src/__tests__/components/Users/SearchResult.test.tsx
ui/src/components/Users/SearchResult/index.tsx

The purpose of this PR was to remove spurious dot appearing on the user search result
---
As per [OCT-306](https://jiscdev.atlassian.net/browse/OCT-306)
--- 
Updated /ui/src/__tests__/Users/SearchResult.test.tsx
---
BEFORE
AFTER

OCT-306 Author search - spurious dot appearing after first name

---

api/package.json
api/prisma/seeds/index.ts
api/prisma/seeds/users.ts
api/src/components/user/__tests__/getUsers.test.ts
api/src/components/user/service.ts

The purpose of this PR was to remove unnecessary response load when searching for users
---
As per [OCT-441](https://jiscdev.atlassian.net/browse/OCT-441)
Get Users
✓ Get all users (896 ms)
✓ Get first 10 users if "limit" param is not provided (688 ms)
✓ Get first 2 users (681 ms)
✓ Get first 2 users which have their first or last name "Test" (677 ms)
✓ Get "Science Octopus" user by searching for "Science" (666 ms)
✓ Returns no user if searching for incomplete firstName/lastName (1129 ms)
---

OCT-441 Author Browse returning all publications and failing with Science Octopus

---

infra/create-app/int.tfvars
infra/create-app/prod.tfvars
infra/modules/postgres/main.tf

The purpose of this PR was to upgrade postgres to version 12.12 for straight upgrade to 14.5.
---
Per [OCT-451](https://jiscdev.atlassian.net/browse/OCT-451?atlOrigin=eyJpIjoiNjEwZTVmNGI2YTQyNGM1NDlkYzQyNWExZWQ4MTg3ZmYiLCJwIjoiaiJ9)

OCT-451 Upgrade postgres (12.12)

---

api/src/components/publication/schema/getAll.ts
api/src/components/publication/service.ts
api/src/lib/interface.ts
e2e/tests/LoggedIn/browse.e2e.spec.ts
e2e/tests/LoggedOut/browse.e2e.spec.ts
ui/src/components/Publication/Card/index.tsx
ui/src/pages/browse.tsx

The purpose of this PR was to fix /browse page not showing latest publications
---
As per [OCT-296](https://jiscdev.atlassian.net/browse/OCT-296)
Fixed e2e tests for /browse page
---
BEFORE
AFTER
[OCT-296]: https://jiscdev.atlassian.net/browse/OCT-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OCT-296]: https://jiscdev.atlassian.net/browse/OCT-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-296 Latest publications not showing in order

---

ui/src/pages/publications/[id]/index.tsx

The purpose of this PR was to fix "statements" html text not rendering correctly on the publication page
---
As per [OCT-472](https://jiscdev.atlassian.net/browse/OCT-472)
---
BEFORE
AFTER
[OCT-472]: https://jiscdev.atlassian.net/browse/OCT-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OCT-472]: https://jiscdev.atlassian.net/browse/OCT-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-472 <strong> tag displayed in ethical statement

---

ui/src/components/Button/index.tsx
ui/src/components/IconButton/index.tsx
ui/src/components/Publication/Creation/Review.tsx
ui/src/layouts/BuildPublication.tsx
ui/src/lib/helpers.tsx

The purpose of this PR was to change "Preview" button restrictions to allow users to preview a draft publication after they filled the title and the main text of it
---
As per [OCT-277](https://jiscdev.atlassian.net/browse/OCT-277)
---
---
[OCT-277]: https://jiscdev.atlassian.net/browse/OCT-277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-277 Preview page - remove restrictions

---

api/src/components/image/service.ts
e2e/tests/LoggedIn/search.e2e.spec.ts
e2e/tests/PageModel.ts
e2e/tests/helpers.ts
ui/src/pages/search/publications/index.tsx

Correct browser back button functionality when viewing filtered publications
When on a publication page accessed from filtered search results clicking browser back button returns user to those search results NOT a fresh blank search. 
e2e tests added to check that search term query and date query is persisted in URL after clicking a publication then clicking browser back btn:

OCT-448 Publication Search back button behaviour

---

api/src/components/image/service.ts
api/src/lib/email.ts

Correct/standardise the image sizes sent as part of the standardHTMLEmailTemplate
Achieved with inline styling
Based on css rules from the head of the template:
header image should be width: 40px;
footer images should be width: 45px;
---

OCT-488 Image size issue in emails

---

api/serverless.yml
api/src/components/coauthor/__tests__/updateCoAuthor.test.ts
api/src/components/coauthor/controller.ts
api/src/components/coauthor/routes.ts
api/src/components/coauthor/schema/index.ts
api/src/components/coauthor/schema/updateConfirmation.ts
api/src/components/coauthor/service.ts
api/src/lib/email.ts
e2e/playwright.config.ts
e2e/tests/LoggedIn/browse.e2e.spec.ts
e2e/tests/LoggedIn/livePublication.e2e.spec.ts
e2e/tests/LoggedIn/login.e2e.spec.ts
e2e/tests/LoggedIn/profile.e2e.spec.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/LoggedIn/search.e2e.spec.ts
e2e/tests/LoggedIn/zRevokeOrcidAccess.spec.ts
e2e/tests/LoggedOut/livePublication.e2e.spec.ts
e2e/tests/PageModel.ts
e2e/tests/helpers.ts
ui/src/pages/publications/[id]/index.tsx

The purpose of this PR was to update PATCH /publications/{id}/coauthor endpoint in order to send email notifications to the main author whenever a co-author approves the invitation.
---
As per [OCT-251](https://jiscdev.atlassian.net/browse/OCT-251)
---
Added e2e tests for co-authors approval and triggered notifications
---
[OCT-251]: https://jiscdev.atlassian.net/browse/OCT-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-251 Email notifications - send email when co-author approves

---

api/src/components/coauthor/controller.ts

The purpose of this PR was to fix co-author rejecting same invitation multiple times and triggering a notification every time they do that.
---
---
---

OCT-337 Email notifications - email when co-author is denies/is removed - FIX

---

api/src/lib/email.ts

The purpose of this PR was to fix image size on old outlook email clients.
All the other styles issues in the old outlook client will be ignore because they require much more time and effort to fix and there's no guaranteed result
---
---
---
BEFORE
AFTER

OCT-289 Inconsistent email formatting - OLD OUTLOOK IMAGE SIZE FIX

---

api/src/components/coauthor/controller.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
ui/src/components/ApprovalsTracker/index.tsx
ui/src/components/Publication/Creation/CoAuthor.tsx
ui/src/components/Publication/Creation/MainText.tsx
ui/src/contexts/ConfirmationModal.tsx
ui/src/layouts/BuildPublication.tsx
ui/src/pages/account.tsx
ui/src/pages/publications/[id]/index.tsx

The purpose of this PR was to offer corresponding authors a way to edit unconfirmed authors emails
---
As per [OCT-528](https://jiscdev.atlassian.net/browse/OCT-528)
---
Added e2e test to demo the functionality
---
[OCT-528]: https://jiscdev.atlassian.net/browse/OCT-528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-528 Correct co-author emails

---

api/src/components/coauthor/controller.ts

The purpose of this PR was to fix a bug where the reminders were not able to be sent due the publication status being in 'LOCKED' rather than 'DRAFT' when initially created.

OCT-521 - Reminder fix

---

ui/src/components/Nav/Desktop/index.tsx
ui/src/components/Nav/index.tsx
ui/src/lib/interfaces.ts
ui/src/pages/index.tsx

The purpose of this PR was to make the guidance more obvious.
---
As per [OCT-595](https://jiscdev.atlassian.net/browse/OCT-595?atlOrigin=eyJpIjoiNjM0ODE3N2VmMjk4NGVkYzk5YmZkNTViM2NmMzk3MmQiLCJwIjoiaiJ9)
Comment on ticket:
> I have spoken to Tim about the positioning of the “Author Guide” button - This will no longer be to the right to the search, instead the order will be: Learn More - Author Guide - Search
[OCT-595]: https://jiscdev.atlassian.net/browse/OCT-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-595 - Make guidance more obvious

---

e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/PageModel.ts
ui/src/components/ApprovalsTracker/index.tsx
ui/src/components/Publication/ActionBar/index.tsx
ui/src/components/Publication/SimpleResult/index.tsx
ui/src/components/index.tsx
ui/src/lib/helpers.tsx
ui/src/pages/publications/[id]/index.tsx

The purpose of this PR was to add an "action bar" on the publication page while the publication it's locked for approvals
The second 'Publish' button was removed from the bottom of the Approvals Tracker table since it's not needed anymore.
---
As per [OCT-581](https://jiscdev.atlassian.net/browse/OCT-581)
---
Updated e2e tests.
---
[OCT-581]: https://jiscdev.atlassian.net/browse/OCT-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-581 Author actions bar

---

api/src/lib/email.ts

The purpose of this PR was to update co-author invitation email text
---
As per [OCT-573](https://jiscdev.atlassian.net/browse/OCT-573)
---
---
[OCT-573]: https://jiscdev.atlassian.net/browse/OCT-573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-573 Remove incorrect text from author invite email

---

ui/src/lib/helpers.tsx

The purpose of this PR was to add timezone name (GMT) on the Approvals Tracker table when sending reminders to co-authors
---
As per [OCT-574](https://jiscdev.atlassian.net/browse/OCT-574)
---
---
BEFORE
AFTER
[OCT-574]: https://jiscdev.atlassian.net/browse/OCT-574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-574 Display GMT on "Reminder sent" text

---

ui/src/components/ApprovalsTracker/index.tsx

The purpose of this PR was to move Acceptance Tracker bottom row outside of the table so it doesn't scroll with the table on mobile devices.
The bottom row still needs to visually look as part of the table.
---
As per [OCT-604](https://jiscdev.atlassian.net/browse/OCT-604)
---
---
[OCT-604]: https://jiscdev.atlassian.net/browse/OCT-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-604 Displaying the acceptance tracker's completion row without a horizontal scroll

---

api/prisma/seeds/publications.ts
api/src/components/coauthor/__tests__/requestApproval.test.ts
api/src/components/coauthor/__tests__/sendApprovalReminder.test.ts
api/src/components/coauthor/controller.ts
api/src/components/coauthor/service.ts
api/src/components/publication/__tests__/updateStatus.test.ts
api/src/components/publication/controller.ts
api/src/components/publication/schema/updateStatus.ts
api/src/components/publication/service.ts
api/src/components/user/__tests__/getUserPublications.test.ts
api/src/lib/helpers.ts
api/src/lib/interface.ts
ui/src/layouts/BuildPublication.tsx

The purpose of this PR was to prevent publications from being LOCKED without filling out the required fields like title, main text, co-authors list and so on...
---
As per [OCT-588](https://jiscdev.atlassian.net/browse/OCT-588)
---
---
[OCT-588]: https://jiscdev.atlassian.net/browse/OCT-588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-588 API Request approval not checking completion

---

api/src/components/publication/controller.ts
api/src/lib/helpers.ts
api/src/lib/interface.ts
api/src/scripts/updateDoi.ts

The purpose of this PR is to send the references to datacite so they are retained on the DOI's data. This PR contains the following changes: 
- The references are passed into the `updateDOI` helper function in the api 
- The references with DOIs are combined with the linked publications and are sent as `relatedIdentifiers`. Any references without DOIs are sent as `relatedItems` 
- The `updateDOINames` script's name has been changed to `updateDoi` and the references are being pulled and passed through the `updateDOI` script
---
As Per [OCT-611](https://jiscdev.atlassian.net/browse/OCT-611?atlOrigin=eyJpIjoiZjIwODQ3MjhiN2E5NDUxYzk3ZTI2NmJmZWE5OWY1YzUiLCJwIjoiaiJ9)
---
- Create a publication with several references (both with and without DOIs) 
- Publish 
- Login to [our test …

Sending referenced works to datacite

---

api/package-lock.json
api/package.json
ui/package-lock.json
ui/package.json

The purpose of this PR was to apply some dependency updates to fix critical security vulnerabilities to some subdependencies. I have done this by adding them as ordinary dependencies. In future when we are using node v16+ and npm 8+, this can be done more elegantly by adding an "overrides" section to package.json.
---
Update the following dependencies:
- UI
- minimist to >= 1.2.6
- underscore to >= 1.12.1
- API
- @xmldom/xmldom to >= 0.7.7
---
API:
UI:
---

Critical security updates

---

infra/create-app/main.tf
infra/create-app/vars.tf
infra/modules/elasticsearch/main.tf
infra/modules/sns/main.tf
infra/modules/sns/outputs.tf
infra/modules/sns/vars.tf
infra/modules/sqs/main.tf
infra/modules/sqs/vars.tf

This PR created the Terraform for the sqs queue, sns topics, cloud watch alarm. The only thing missing is the link to the sqs queue and the lambda to trigger generation, this can be added either via terraform or manually when this is confirmed tested and working correctly when merging in the second part of this ticket, the code changes [here](https://github.com/JiscSD/octopus/pull/386)
Currently we only have one slack channel, so will need another created to send emails to for testing on int.
We check in our tfvar file, so you will need to add this line to it before running the terraform:
`slack_channel_email = <email_string>`
---
As Per [OCT-614](https://jiscdev.atlassian.net/browse/OCT-614?atlOrigin=eyJpIjoiMTI3YTNlNzg0OWQ3NGU2ZWE5NmE4NzFhYjA4OGY2MjIiLCJwIjoiaiJ9)
[OCT-614]: …

OCT-614 - Queued generation of PDFs - Terraform

---

e2e/tests/LoggedIn/publish.e2e.spec.ts

The purpose of this PR was to make a small correction our e2e tests so that they don't fail to locate the accept button in our coauthor invitation emails.

update button text from coauthor invitation email

---

api/package.json

The purpose of this PR was to remove source-map-support from package.json as it's listed as a red dependency and has not received support for 2 years. Also, we don't seem to actually use it. 
---
As per [OCT-666](https://jiscdev.atlassian.net/browse/OCT-666?atlOrigin=eyJpIjoiNDQxZDRmNzdmMmRkNGNhYWE3MzFmZjM1YjRkMDBkMTEiLCJwIjoiaiJ9)
---
[OCT-666]: https://jiscdev.atlassian.net/browse/OCT-666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-666 😈 Remove source-map-support - Red Dependency 

---

e2e/package-lock.json
e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/LoggedOut/profile.e2e.spec.ts
ui/package-lock.json
ui/package.json

The purpose of this PR was to remove underscore, because it is an unused dependency that has security advisories against it.
I have also cherry picked [this commit](https://github.com/JiscSD/octopus/pull/423/commits/5ba4eaca71d8f70a0f66285c7f523ad7e7de75d2) made by Florin so that I could run end to end tests. I had to make a few more changes to them as well to detect author names more specifically and to stop trying to manually preview the publication after requesting approval (which happens automatically).
The e2e package-lock change seems to just be the new lockfile version as a result of installing dependencies using node 16 (as directed in package.json) so I have included it.
---
Underscore is no longer a UI dependency.
---
---

Remove underscore

---

ui/src/pages/index.tsx

The purpose of this PR was to change the copy on the homepage so it reads: 
> Octopus is a new publishing platform for scholarly research. Funded by UKRI – the UK government research funder.
---
As per [OCT-704](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-704)
---
---
[OCT-704]: https://jiscdev.atlassian.net/browse/OCT-704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Break up sentence on home page blurb

---

api/prisma/seeds/publications.ts
api/src/components/coauthor/__tests__/linkCoAuthor.test.ts
api/src/components/coauthor/controller.ts

The purpose of this PR was to add an extra check on the api in order to prevent coauthors accepting an invitation using a different account
---
---
---
---

OCT-560 Invitation emails can be accepted by users who's email doesn't match

---

e2e/.env.example
e2e/package-lock.json
e2e/package.json
e2e/tests/helpers.ts
ui/package-lock.json
ui/package.json
ui/src/lib/api.ts

The purpose of this PR was to upgrade UI and e2e node version to 18
---
upgrade to node 18 or whatever latest LTS version there is
need to make sure amplify and API builds support same version)
---
---
---

OCT-654 upgrade node to LTS for UI and e2e tests

---

ui/src/components/Nav/Mobile/index.tsx

The purpose of this PR was to fix the mobile nav bar bug where the subitems menu closes the whole navbar when a user clicks to expand. 
This turned out to be a pretty simple fix and looks like was a bug in our code. I've changed it so the `setOpen` state is set to true when the user clicks it as previously it was being set to false. 
---
As per [OCT-706](https://github.com/JiscSD/octopus/pull/378/files)
---
---
https://github.com/JiscSD/octopus/assets/100135505/2f52a86c-b147-43d5-9b21-12372df3d529
[OCT-706]: https://jiscdev.atlassian.net/browse/OCT-706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Dropdown menu not working except on a full width desktop display

---

api/docker-compose.yml
api/package-lock.json
api/package.json
docker-compose.yml
infra/modules/elasticsearch/main.tf

The purpose of this PR was to update opensearch to the latest version.
---
- Opensearch is on version 2.7
---
I have confirmed with terraform plan that this would cause the opensearch instance to be changed in-place so it should not affect our search indexes apart from a brief downtime to apply the update.
---

OCT-650 - update opensearch

---

api/package-lock.json
ui/src/lib/helpers.tsx
ui/src/pages/search/publications/index.tsx

The purpose of this PR was to add a new _Select/deselect all_ checkbox on the publication search page.
Fixed an existing bug regarding checkboxes selection. For a split second, wrong results were showing up when selecting new publication types, until the api call returned the new data.
---
As per [OCT-623](https://jiscdev.atlassian.net/browse/OCT-623)
---
---
---
[OCT-623]: https://jiscdev.atlassian.net/browse/OCT-623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-623 Select/deselect all publication types in search

---

ui/src/lib/api.ts
ui/src/lib/types.ts
ui/src/pages/search/authors/index.tsx

The purpose of this PR was to fix a bug where if the user switches to the author search on the search page, the dropdown for search type stays on “Publication”. This prevents users from switching back to the publications search except by navigating away and back to the search page.
The reason for this bug is that the state wasn't being updated when the user changes their selection. 
---
See [OCT-721](https://jiscdev.atlassian.net/jira/software/projects/OCT/boards/836?selectedIssue=OCT-721)
---
---
https://github.com/JiscSD/octopus/assets/100135505/6588ebbb-31a9-4431-bfe5-d9aa7e0e9c15
[OCT-721]: https://jiscdev.atlassian.net/browse/OCT-721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Author search dropdown not changing properly - UI 

---

ui/src/components/Publication/Creation/LinkedPublications.tsx

The purpose of this PR was to stop options in the publication link combobox being unreachable because the end of the scroll bar is obscured.
---
The scrollbar can be scrolled from top to bottom and all options are fully shown.
---
---
---
Note the options list now extends past the bottom of the section tag containing the form. Previously the overflow was hidden behind the footer.

OCT-473: stop options from being obscured

---

infra/modules/bastion/main.tf

The purpose of this PR was to fix a small issue in terraform where it was possible for the bastion EC2 instance to be assigned an amazon machine image that is not compatible with its architecture type (e.g. arm64 vs. x86_64).
---
Bastions are provisioned with an AMI that uses x86_64 architecture to match the t3.small instance type.
---

OCT-727: Specify AMI architecture to match instance type (t3.small)

---

infra/modules/bastion/main.tf

The purpose of this PR was to make a quick fix to terraform. Before this change, the names of these resources were clashing as int and prod are in the same AWS account and both trying to create resources with the same name.

Use names scoped to environment

---

api/serverless.yml

The purpose of this PR was to use Lambda [Provisioned Concurrency](https://aws.amazon.com/about-aws/whats-new/2019/12/aws-lambda-announces-provisioned-concurrency/) for some of the most used lambdas in order to keep them warm. 
The code has been tested on int and it seems to work fine.
---
As per [OCT-709](https://jiscdev.atlassian.net/browse/OCT-709)
---
---
[OCT-709]: https://jiscdev.atlassian.net/browse/OCT-709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-709 Keeping lambdas warm to improve site performance

---

api/src/components/topic/service.ts
ui/src/lib/interfaces.ts
ui/src/pages/topics/[id]/index.tsx

The purpose of this PR was to add a new section on the topic page called: **Research problems linked to this topic**
On this section, users can see links to all research problems that are linked to that particular topic.
---
As per [OCT-730](https://jiscdev.atlassian.net/browse/OCT-730)
---
---
---
[OCT-730]: https://jiscdev.atlassian.net/browse/OCT-730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-730 Add an indication of child research problems on topic pages

---

api/serverless.yml

The purpose of this PR was to remove Lambda Provisioned Concurrency due to increased aws costs for lambdas
---
---
---
---

Turn off Lambda Provisioned Concurrency

---

api/src/lib/helpers.ts
api/src/lib/interface.ts

The purpose of this PR was to update the publication PDF template to display a deduplicated list of affiliations from the publication's coauthors, instead of the current publication-level affiliations (which have been migrated to coauthor level and removed).
---
- Each author affiliation is listed in a combined list under the “affiliations” section of publication PDFs
- The list is alphabetised by affiliation name
- The list is de-duplicated by affiliation name
---
---
---

OCT-743 - Listing author affiliations on PDFs

---

api/src/components/publication/controller.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
ui/src/components/Publication/Creation/LinkedItems/index.tsx

The purpose of this PR was to correct a bug with the original work on OCT-620. Only research problems should have the option to link to a topic, but in testing, any publication type could do this.
---
Only research problems can be linked to a topic using the UI.
---

OCT-620 - stop non-problem publications being linkable to topics

---

.github/workflows/ui-tasks.yml
api/package-lock.json
e2e/mocks/contentful_blog_posts.json
e2e/tests/LoggedOut/blog.e2e.spec.ts
e2e/tests/PageModel.ts
e2e/tsconfig.json
ui/.env.example
ui/package-lock.json
ui/package.json
ui/src/components/BlogCard/index.tsx
ui/src/components/Footer/index.tsx
ui/src/components/index.tsx
ui/src/config/urls.ts
ui/src/lib/contentfulClient.ts
ui/src/lib/types.ts
ui/src/pages/blog/index.tsx
ui/tsconfig.alias.json

The purpose of this PR was to create a new /blog page, where we display blog teasers fetched from Contentful API as grid.
The blogs are wrapped with a link to their individual blog page (will be implemented in OCT-740)
---
As per [OCT-734](https://jiscdev.atlassian.net/browse/OCT-734)
---
---
---
[OCT-734]: https://jiscdev.atlassian.net/browse/OCT-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-734 Creation of an overall blog page

---

api/package-lock.json
ui/src/components/BlogCard/index.tsx
ui/src/config/urls.ts
ui/src/config/values.ts
ui/src/lib/types.ts
ui/src/pages/blog/[slug].tsx
ui/src/pages/blog/index.tsx

The purpose of this PR was to create the individual blog page.
For improved SEO and performance, each blog post is pre-rendered at build time with Nextjs "[getStaticPaths](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-paths)" and "[getStaticProps](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-props)" instead of being fetched.
For new blog posts and updates I have used Nextjs [ISR](https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration)
PS. - this branch needs to be rebased with main after [OCT-734](https://jiscdev.atlassian.net/browse/OCT-734) is being merged
---
As per [OCT-740](https://jiscdev.atlassian.net/browse/OCT-740)
---
---
Tested the generation of static pages …

OCT-740 Creation of an individual blog page

---

api/package-lock.json
ui/src/components/BlogCard/index.tsx
ui/src/components/Nav/index.tsx

The purpose of this PR was to add a nav link to the blog page.
This is branched off from OCT-740 because it needed the URL config for the blog page so it should probably be merged after that.
---
As per [OCT-733](https://jiscdev.atlassian.net/browse/OCT-733?atlOrigin=eyJpIjoiY2MxN2QxNTM5NjBkNDYxMTlmNjRkYTA2Yjk5ZTgzZWYiLCJwIjoiaiJ9)
---
[OCT-733]: https://jiscdev.atlassian.net/browse/OCT-733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-733 - Blog link in nav bar

---

infra/modules/s3/main.tf

The purpose of this PR was to fix a small issue with the pubrouter terraform where an IAM role name was the same when using different workspaces, causing "already exists" conflicts when attempting to deploy.
---
Terraform deploy works on multiple environments without clashing resource names.
---

OCT-762: differentiate role name by environment

---

ui/src/pages/_document.tsx

The purpose of this PR was to address an issue that was in the original work for this item. The og:title and og:description meta tags were set at the document level and were overriding the values set per page.
---
As per [OC-95](https://jiscdev.atlassian.net/browse/OC-95)
---
[OC-95]: https://jiscdev.atlassian.net/browse/OC-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OCT-728: Rremove og title and description from document level

---

api/src/components/publication/controller.ts
api/src/components/publication/service.ts
api/src/lib/interface.ts
ui/src/components/Publication/Visualization/index.tsx
ui/src/lib/interfaces.ts

The purpose of this PR was to rework GET /publications/{id}/links endpoint used for visualisation so that it returns latest LIVE version of each link. Removed unnecessary fields like "content", "publicationStatus", etc from the response since they are not needed for Visualisation.
Had to do some minor changes on the UI in order to match with the endpoint response.
---
As per [OC-697](https://jiscdev.atlassian.net/browse/OC-697)
---
---
---
[OC-697]: https://jiscdev.atlassian.net/browse/OC-697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-697 Include all live publications when getting links

---

api/src/components/coauthor/__tests__/createCoAuthor.test.ts
api/src/components/coauthor/controller.ts
api/src/components/coauthor/service.ts
ui/src/components/Publication/Creation/CoAuthor.tsx

The purpose of this PR was to ensure that co-authors' email addresses are saved in lower case to prevent situations where their email from their account (always lower case) is checked against the saved email (potentially mixed case) and incorrectly judged to be different.
Also included a few minor tweaks - the main one was changing the emailDuplicated state variable during coauthor creation so that it's true when there is a duplicate email, which makes more sense.
---
We should always store emails in a lowercase format.
---
---
UI:
E2E:
API:

OC-711: Co-authors cannot accept invitations

---

ui/src/components/Publication/SidebarCard/Actions/index.tsx
ui/src/components/Publication/SidebarCard/Sections/index.tsx
ui/src/components/index.tsx

The purpose of this PR was to remove the "Write a linked {publication type}" from the /publications/{id} page when the publication status is DRAFT. Going by the reasoning in the item I have used a slightly different condition - where status is not LIVE, as we wouldn't want these options to show on LOCKED publications either.
I haven't changed the API as that already prevents links from being saved where the publication being linked to is not LIVE.
---
As per [OC-638](https://jiscdev.atlassian.net/browse/OC-638)
---
---
UI:
E2E:
---
The Actions section of the sidebar isn't shown when the publication isn't LIVE.
[OC-638]: https://jiscdev.atlassian.net/browse/OC-638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-638: Hide "Write a linked publication" option on all draft publications

---

api/src/components/coauthor/controller.ts
api/src/lib/email.ts

The purpose of this PR was to add a new notification type when co-authors cancel their approvals after they approved initially.
---
As per [OC-153](https://jiscdev.atlassian.net/browse/OC-153)
---
---
---
[OC-153]: https://jiscdev.atlassian.net/browse/OC-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-153 Co-authors changing their mind triggers "denied involvement" email

---

api/Dockerfile
api/src/components/flag/controller.ts
ui/src/components/ApprovalsTracker/index.tsx
ui/src/components/BlogCard/index.tsx
ui/src/components/Flag/Comment/index.tsx
ui/src/components/Flag/Preview/index.tsx
ui/src/components/PageSubTitle/index.tsx
ui/src/components/Publication/BookmarkedPublications/index.tsx
ui/src/components/Publication/Creation/LinkedItems/LinkedPublicationRow.tsx
ui/src/components/Publication/Creation/LinkedItems/LinkedPublicationsCombobox.tsx
ui/src/components/Publication/SidebarCard/Actions/index.tsx
ui/src/components/Publication/SimpleResult/index.tsx
ui/src/pages/blog/[slug].tsx
ui/src/pages/publications/[id]/flag/[flagId]/index.tsx

The purpose of this PR was to display an informative error message when the user attempts to create a flag that they have already created one of the same type for on the current publication. The API was already sending a message but the UI was not set up to display it.
I ran into a hydration error while working on this so made some adjustments to prevent these wherever we are using dates/times formatted with toLocaleString().
---
As per [OC-633](https://jiscdev.atlassian.net/browse/OC-633).
---
---
E2E:
UI:
API:
---
[OC-633]: https://jiscdev.atlassian.net/browse/OC-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-633: Change error message when users raise a duplicate red flag

---

ui/src/components/Publication/Creation/LinkedItems/LinkedPublicationsCombobox.tsx

The purpose of this PR was to add a way to show more information about a publication to the user when they are considering whether to link to it, and perhaps the title alone is not enough information.
---
As per [OC-75](https://jiscdev.atlassian.net/browse/OC-75)
Note: although this solution doesn't show the preview on focus, it shows on hover and is available to assistive technologies on focus, so agreed with PO that this is a fair compromise in order to achieve this with a neat + standard solution as opposed to something complex and homebrew.
---
---
UI:
E2E:
[OC-75]: https://jiscdev.atlassian.net/browse/OC-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-75: Preview link candidate details on hover

---

api/src/lib/helpers.ts
api/src/lib/interface.ts

The purpose of this PR was to fix affiliations mapping when those affiliations were added by trusted organisations and not by the user himself. It seems the "source" values come under "source-orcid" when the affiliation is added by the user himself, but if the affiliation was added by an organisation, the "source" values come as "source-client-id". 
---
As per [OC-726](https://jiscdev.atlassian.net/browse/OC-726)
---
---
---
[OC-726]: https://jiscdev.atlassian.net/browse/OC-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-726 Some users are unable to load affiliations

---

ui/src/components/Nav/index.tsx
ui/src/pages/index.tsx

The purpose of this PR was to add a link to the Research Culture Report page on the homepage and also to update the link text into the nav bar from 'Report' to 'Research Culture Report'
---
As per [OC-728](https://jiscdev.atlassian.net/browse/OC-728)
---
---
---
[OC-728]: https://jiscdev.atlassian.net/browse/OC-728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-728 Research culture report homepage link

---

api/package.json
api/prisma/createVersionedDOIs.ts
api/prisma/migrations/20231026083835_added_version_doi/migration.sql
api/prisma/schema.prisma
api/src/components/publicationVersion/controller.ts
api/src/components/publicationVersion/service.ts
api/src/lib/helpers.ts
ui/src/components/Publication/SidebarCard/General/index.tsx
ui/src/lib/interfaces.ts
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to create a custom script in order to generate versioned DOIs and update existing (canonical) DOIs with the new generated DOIs for versions. Also on the API, when publishing, a new DOI will be generated for v1 and the relation between canonical DOI and v1 DOI will be updated on datacite as well.
For this specific task I had to duplicate /publications/[id] page and put it under /publications/[id]/versions/[versionId]
On prod users will still use the old publication page but on int and locally they will be redirected from /publications/[id] to /publications/[id]/versions/[versionId] until we develop further versioning functionalities and they are ready to go live on prod, but until then, individual tasks will be available for testing on int.
---
As per …

OC-389 Versioned DOIs

---

api/src/components/publicationVersion/controller.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/helpers.ts
ui/src/lib/api.ts
ui/src/pages/publications/[id]/index.tsx
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to redirect anonymous users to login when they attempt to view a publication that exists only in draft/locked status. This required a small API change so that we can determine from the API response status whether the publication exists in one of these states, or doesn't exist at all (which up to now both returned 404 status).
Also made a couple of end to end test tweaks as some of them were failing due to some recent versioning changes.
---
- When a user is not logged in and navigates directly to a draft publication, they should be redirected to the ORCiD log in, and directed back to the publication page.
- If the user has permission to view it, they see the draft publication page as normal
- If the user does not have permission to view it, they see a 404
--- …

OC-721: Require login before checking whether a user has permission to view a draft

---

ui/src/pages/publications/[id]/index.tsx
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to stop the bookmark button when a draft/locked publication is being viewed.
---
- We can allow users to bookmark their own LIVE publications, but the bookmark button should be hidden in DRAFT (and LOCKED).
---
---
UI
E2E
---
This shows a draft publication being viewed without the bookmark button.

OC-717: Bookmark button visible while in DRAFT

---

api/src/components/publication/__tests__/getPublication.test.ts
api/src/components/publication/controller.ts
api/src/lib/helpers.ts
api/src/lib/interface.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/PageModel.ts
ui/src/components/Publication/VersionsAccordion/VersionsAccordion.tsx
ui/src/components/index.tsx
ui/src/lib/interfaces.ts
ui/src/lib/types.ts
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to add a version switch accordion on the publication page
---
As per [OC-392](https://jiscdev.atlassian.net/browse/OC-392)
---
---
---
[OC-392]: https://jiscdev.atlassian.net/browse/OC-392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-392 Switching between displayed version

---

ui/src/components/Publication/VersionsAccordion/VersionsAccordion.tsx
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to put the aforementioned message in a more prominent place.
---
- If a version of the publication that is not the latest live version, the message “A newer version of this publication exists” and the corresponding warning icon are displayed below the author list 
---
---
UI
E2E
---

OC-737: Move "A newer version of this publication exists" message

---

ui/src/components/Nav/index.tsx

The purpose of this PR was to fix a z-index issue that occurs on mobile nav dropdown.
I've also replaced normal link with FlickerLessLink component because I noticed the flicker we solved on the desktop nav is still visible if the browser window get's small enough.
---
As per [OC-733](https://jiscdev.atlassian.net/browse/OC-733)
---
---
---
[OC-733]: https://jiscdev.atlassian.net/browse/OC-733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-733 Nav dropdowns appearing behind vis content

---

e2e/tests/LoggedIn/publish.e2e.spec.ts
ui/src/components/Publication/ActionBar/index.tsx
ui/src/components/Publication/SimpleResult/index.tsx
ui/src/components/Publication/VersionsAccordion/VersionsAccordion.tsx
ui/src/hooks/index.ts
ui/src/hooks/useControlRequest.tsx
ui/src/hooks/useCreateNewVersion.ts
ui/src/lib/types.ts
ui/src/pages/publications/[id]/versions/[versionId].tsx

_Note! This branch needs to be rebased with main after #541  is being merged_
The purpose of this PR was to provide options for create/edit draft versions from 'Versions' dropdown on the publication page. And also provide option for co-authors to request control over the new version
---
As per [OC-727](https://jiscdev.atlassian.net/browse/OC-727)
---
---
---
[OC-727]: https://jiscdev.atlassian.net/browse/OC-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-727 Adding new versions from version switch dropdown

---

api/src/components/event/service.ts
api/src/lib/email.ts

The purpose of this PR was to add notification that's being sent to old corresponding author when the ownership over a publication version is automatically transferred.
---
---
---
---

OC-736 Notify old corresponding author of automatic replacement

---

ui/src/components/Video/HTML/index.tsx
ui/src/pages/about.tsx

The purpose of this PR was to add the new octopus promo video under /about page
Poster/thumbnail was confirmed with PO
---
Per [OC-734](https://jiscdev.atlassian.net/browse/OC-734)
---
---
---
[OC-734]: https://jiscdev.atlassian.net/browse/OC-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-734 Add new promo video to Octopus

---

api/src/components/event/controller.ts
api/src/components/event/service.ts
api/src/components/publicationVersion/controller.ts
api/src/components/user/controller.ts
api/src/lib/email.ts

The purpose of this PR was to add a new notification for superseded co-authors when publication version ownership is transferred.
---
As per [OC-735](https://jiscdev.atlassian.net/browse/OC-735)
---
---
---
[OC-735]: https://jiscdev.atlassian.net/browse/OC-735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-735 Email co-authors when corresponding authorship is transferred

---

api/src/components/user/controller.ts
api/src/components/user/schema/getPublications.ts
api/src/components/user/service.ts
api/src/lib/interface.ts
e2e/tests/LoggedIn/profile.e2e.spec.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/LoggedIn/z_account.e2e.spec.ts
e2e/tests/PageModel.ts
ui/src/pages/account.tsx

The purpose of this PR was to add filters for DRAFT/LIVE versions on `/account` page
---
As per [OC-740](https://jiscdev.atlassian.net/browse/OC-740)
---
---
---
[OC-740]: https://jiscdev.atlassian.net/browse/OC-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-740 Filtering the account page

---

api/src/components/coauthor/service.ts
api/src/components/funder/service.ts
api/src/components/link/service.ts
api/src/components/publicationVersion/service.ts
api/src/components/reference/service.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/PageModel.ts

The purpose of this PR was to make sure that all actions a user would understand to be "updating a publication (version)" update the updatedAt field on the publication version model in the database. Then when this is surfaced in the application it will match up to the actions they have taken.
---
The following items should affect the last updated date of publications on the account page:
1. Edits to the publication version
2. All related entities
3. Funder information
4. Affiliations changes (co author and corresponding author)
5. Co-author approval
6. Co-author changing their mind
7. Co-author denying involvement
8. Co-author being added or removed
9. Publication being locked or unlocked
10. Transfers of corresponding authorship
---
---
API:
E2E:

OC-742: Ensure all edits affect "Last Updated" on account page

---

e2e/tests/PageModel.ts
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to display parent publications of all types, not just other problems, while viewing a research problem. Before this, if a problem was linked to a non-problem publication, that wasn't shown anywhere on the page when viewing it.
---
- On research problems the “Research problems above this in the hierarchy” is renamed to “Publications above this in the hierarchy”.
- This section includes any publication type of publication (excluding topics) that sit above it in the hierarchy.
---
---
E2E:
UI:

OC-751: Display parent publications on child research problems

---

e2e/tests/LoggedIn/publish.e2e.spec.ts
ui/src/components/Publication/SimpleResult/index.tsx

The purpose of this PR was to adjust some text on the my account page to stop implying that the current author is not actively working on the publication.
Also contains a slight tweak to the logic where:
- user is corresponding author
- publication is locked and awaiting approval
- button shown is changed from edit draft to view draft
And accompanying changes to end to end tests to ensure all still pass.
---
1. If a new draft has been created, co-authors on the latest live version who haven’t confirmed involvement in the new draft version see the message “Someone else has is working on a new draft version, and you do not yet have access to it.” (instead of “Someone else has created a new draft version, and you do not yet have access to it.”)
2. If a new draft version has been created and …

OC-747: Change account page draft being edited wording to imply activity

---

docker-compose.yml

I noticed a small thing after I recreated my docker containers - 3 of them don't start automatically when the docker service starts. Since they come as a group it makes sense for either all of them to start together or none. I added the restart = always setting to these three so that the group will always start up together.

Make sure all containers restart automatically

---

api/package.json
api/prisma/deleteHighLevelTopicBookmarks.ts
api/prisma/seeds/topicsDevSeedData.ts
api/src/components/bookmark/__tests__/createBookmark.test.ts
api/src/components/bookmark/controller.ts
e2e/tests/LoggedIn/topic.e2e.spec.ts
e2e/tests/PageModel.ts
ui/src/pages/topics/[id]/index.tsx

The purpose of this PR was to prevent users from bookmarking god topic and first level topics
---
As per [OC-488](https://jiscdev.atlassian.net/browse/OC-488)
---
---
---
[OC-488]: https://jiscdev.atlassian.net/browse/OC-488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OC-488 Disable bookmarking god problem and 2nd level LOC items

---

e2e/tests/LoggedIn/publish.e2e.spec.ts
ui/src/components/Publication/SimpleResult/index.tsx

The purpose of this PR was to always present confirmed coauthors with both the option to view a draft publication they are on and to request to take control of it. Before this they would have had to navigate to the draft to see the option to request control.
---
- On the account page, confirmed co-authors for a publication that has a draft version see:
- A button to “View draft”
- A button to “Take over editing”
---
---
UI
E2E
---

OC-763: Display "View Draft" and "Take over editing" at once for co-authors

---

api/serverless.yml
ui/README.md
ui/src/pages/sitemaps/static.xml.tsx

The purpose of this PR was to fix some issues that were occurring with the sitemap code from OC-745:
- Lambdas didn't have correct permission to put objects in and list the sitemap S3 bucket
- The method of listing the src/pages directory to get a static pages list doesn't seem to work on amplify. Rather than adapt to that, decided and agreed with PO to base the static pages sitemap on a manually managed list. This also has the advantage of not letting new pages that we wouldn't want to show get included in the sitemap.
---
As per [OC-745](https://jiscdev.atlassian.net/browse/OC-745).
---
[OC-745]: https://jiscdev.atlassian.net/browse/OC-745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixes for OC-745

---

api/src/components/publication/service.ts

The purpose of this PR was to show the most recent publications first on the search page, both to aid in finding new content, and to it clear that the site is active, as currently users will see “S. Octopus, 2 years ago” on the search page by default.
Behaviour after a search term is entered is less important, but whilst no keywords have been entered, the page should be sorted with the most recent publications at the top. This includes (if possible) whilst filters are on for publication date and publication type.
---
- If no query term has been provided (including if filters are in use), the search endpoint should return results in order of publication date, from most to least recent. Otherwise, results should be sorted by opensearch score.
---
---
API
E2E
---

OC-770: Sort search page by recency if no criteria have been entered

---

api/serverless.yml
api/src/components/additionalInformation/__tests__/createAdditionalInformation.test.ts
api/src/components/additionalInformation/controller.ts
api/src/components/publication/controller.ts
api/src/components/publication/schema/getPDF.ts
api/src/components/publicationVersion/controller.ts
api/src/components/publicationVersion/schema/updateStatus.ts
api/src/lib/interface.ts
ui/src/components/Publication/Creation/AdditionalInformation/Form.tsx

The purpose of this PR was to correct an issue brought about by #570. Some path variables in serverless.yml were changed to be clearer, but AWS API gateway doesn't allow you to use two variables with different names in the same path segment. In our case, we had /publications/{id}/... and /publications/{publicationId}/... and a similar conflict with publication versions. This PR is to ensure we are using the same variable names throughout and API gateway won't throw any conflicts (already confirmed with a deploy to int env).
Also added in a small error text change requested by PO.

OC-131 fix: Use same path variable names throughout serverless.yml

---

api/src/components/coauthor/__tests__/linkCoAuthor.test.ts
api/src/components/coauthor/controller.ts
api/src/components/coauthor/schema/link.ts
api/src/components/coauthor/service.ts
api/src/components/user/service.ts
api/src/lib/interface.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/PageModel.ts
ui/src/components/Publication/SimpleResult/index.tsx
ui/src/pages/author-link.tsx

The purpose of this PR was to show a "Confirm Involvement" button to unconfirmed co-authors who view a publication on their account page. This replaces the "Take over editing" button in this scenario and provides users the convenience of being able to confirm their involvement from within the application (compared to using the link from an email).
---
1. If a publication is locked for approval, any unconfirmed authors whose emails are listed on the draft (even on the first version) have that publication listed in their account page (even the draft goes back into “DRAFT” status, and has never been published, and they are unconfirmed).
2. Instead of the “Someone else has created a draft version and you do not yet have access to it” text, text is present reading “<Corresponding author> has …

OC-761: Allow confirmation of involvement from account page

---

api/prisma/createVersionedDOIs.ts
api/prisma/migrations/20240130093815_funder_grant/migration.sql
api/prisma/schema.prisma
api/prisma/seeds/publications.ts
api/src/components/funder/__tests__/createFunder.test.ts
api/src/components/funder/controller.ts
api/src/components/funder/schema/create.ts
api/src/components/funder/service.ts
api/src/components/publication/service.ts
api/src/components/publicationVersion/service.ts
api/src/lib/interface.ts
api/src/scripts/updateDoi.ts

The purpose of this PR was to add a new Grant ID field to funders on the API. This also brings with it new validation requirements - a duplicate funder (i.e. having the same ROR ID or link as an existing funder) can be added, if both the existing funder and new funder have a grant ID, and they are different.
---
- Grant IDs can be added as part of each funder entry
- Validation rules are changed to allow duplicate funders to be added as long as they have different grant IDs
- Update tests
---
---
API:
E2E:

OC-782: API functionality for adding grant IDs

---

api/src/components/publication/service.ts
api/src/lib/helpers.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
ui/src/components/AdditionalInformationCard/index.tsx
ui/src/components/index.tsx
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to display the new additional information fields when viewing a publication webpage and a publication PDF.
---
- On the publication page, immediately below the main text (above the sections for linked publications), a heading is present for “Additional parts of this work hosted elsewhere” with a list of each, displayed with:
- The title in bold
- The description immediately on the line below the title
- The URL for the resource displayed as a hyperlink
- This link should be marked up using the link’s title in the format “Link to <title>”, to be announced to screen readers
- On PDFs, a section is present to display additional information, including the section title “Additional parts of this work hosted elsewhere” in the same font size/style as other heading …

OC-749: Displaying additional information fields on publications

---

ui/src/components/AdditionalInformationCard/index.tsx

The purpose of this PR was to correct an issue with OC-749 not matching the ACs. The link should show the URL of the additional information to make it clearer where people will be taken.
---
- Additional information link text displays the URL of the additional information.
---
---
Before:
After:

OC-749 fix: Change additional info link text

---

ui/src/components/Publication/SimpleResult/index.tsx

The purpose of this PR was to change the account page’s wording so that it distinguishes that the user is not an author on the live version specifically.
---
- On the account page, the text that appears if an author is not on the latest live version, “You are not listed as an author on the latest version” now reads “You are not listed as an author on the latest published version”.
---
---
E2E:
UI:
---

OC-781: Change "You are not listed as an author" text

---

ui/src/lib/interfaces.ts
ui/src/pages/search/authors/index.tsx

The purpose of this PR was to stop the author search from briefly showing a different page of results after changing page.
This was happening because the results were rendering with an animation before the request for the new page had finished and been validated.
I also included some general tidying up of the page and bringing it more in line with the topics search page which was written more recently (this is all in the 2nd commit).
---
- The author search doesn't show incorrect results briefly when changing page.
---
---
E2E:
UI:

OC-785: Author search flickers back to first page of results when switching

---

api/src/components/sitemap/controller.ts
api/src/components/sitemap/service.ts
ui/src/lib/api.ts
ui/src/lib/helpers.tsx
ui/src/pages/authors/[id]/index.tsx
ui/src/pages/browse.tsx
ui/src/pages/search/topics/index.tsx
ui/src/pages/sitemap.xml.tsx
ui/src/pages/sitemaps/topics.xml.tsx
ui/src/pages/sitemaps/users.xml.tsx
ui/src/pages/sitemaps/users/[sitemap].tsx

The purpose of this PR was to have sitemaps of a size that google can manage. We need to make sure that they only contain 50,000 URLs. In the case of users, we should develop a solution that can cope with the system having over 50,000 users.
---
- Every 24 hours, a cron job triggers a lambda to generate a sitemap for users which is then stored in an s3 bucket 
- The API endpoint which is used to return XML sitemaps for publications (OC-745) also returns the sitemaps for users
- The sitemaps at /users/[number].xml in an s3 bucket contain links to the “[number]th” 50,000 user in octopus (a consistent sort order between the sitemaps is needed but it doesn’t especially matter what it is). For example, /sitemaps/users/3.xml would contain the 100,001st user up to the 150,000th user.
---
---

OC-746: Generate separate sitemaps per 50k users on back end

---

api/package-lock.json
api/package.json

The purpose of this PR was to apply updates to mitigate two vulnerabilities:
- Update nodemailer to fix: https://app.snyk.io/org/digital-resources/project/cec951e8-deaa-43b3-bffb-ac3d3f1bddcb#issue-SNYK-JS-NODEMAILER-6219989
- Update subdependencies of copy-webpack-plugin to fix: https://app.snyk.io/org/digital-resources/project/cec951e8-deaa-43b3-bffb-ac3d3f1bddcb#issue-SNYK-JS-SERIALIZEJAVASCRIPT-6147607
Additionally, some modules are flagged as having newer versions, and although our versions don’t have vulnerabilities, we are recommended to update to them:
- @opensearch-project/opensearch from 2.3.1 to 2.5.0
- @middy/core from 4.6.2 to 4.7.0
- @middy/do-not-wait-for-empty-event-loop from 4.6.2 to 4.7.0
- @middy/http-json-body-parser from 4.6.2 to 4.7.0
---
Octopus API is using the …

OC-799: Sprint 37 security updates

---

api/src/components/publication/controller.ts
api/src/components/publication/service.ts
api/src/components/publicationVersion/controller.ts
api/src/components/publicationVersion/service.ts
api/src/components/sqs/handler.ts
e2e/tests/LoggedIn/livePublication.e2e.spec.ts
ui/src/components/Publication/SidebarCard/Actions/index.tsx

The purpose of this PR was to send an updated record to publications router under the “all versions” DOI when a new version of a publication is published.
Also moved the generatePDF function from the publication service to the publication version service as per the TODO comment.
Some parts of this flow are unavailable locally so the full flow including this part will have to be confirmed on the int environment:
- Triggering PDF generation via SQS messages
- Locally, they're generated when requested, and this won't force a regenerate like the SQS triggered calls will
- Triggering the message to pubrouter when a PDF is put in the S3 bucket
Also fleshed out a basic todo e2e test to confirm that PDFs are generated.
---
Upon the publication of a new version, a new PDF for that version is …

OC-767: Sending new versions to pubrouter

---

ui/src/__tests__/components/PageTitle.test.tsx
ui/src/lib/interfaces.ts
ui/src/pages/search/authors/index.tsx

The purpose of this PR was to fix a bug where entering a query in the "quick search" box on the author search page didn't affect the results.
Added some tests for our PageTitle component.
---
- When a search term is submitted into the author search, results are filtered to match the term against the author's first or last name.
---
---
UI
E2E
---
No query
Query

OC-805: Author search not responding to search terms

---

e2e/.gitignore
e2e/README.md
e2e/playwright.config.ts
e2e/tests/LoggedIn/browse.e2e.spec.ts
e2e/tests/LoggedIn/livePublication.e2e.spec.ts
e2e/tests/LoggedIn/login.e2e.spec.ts
e2e/tests/LoggedIn/profile.e2e.spec.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/LoggedIn/revokeOrcidAccess.spec.ts
e2e/tests/LoggedIn/search.e2e.spec.ts
e2e/tests/LoggedIn/topic.e2e.spec.ts
e2e/tests/LoggedIn/z_account.e2e.spec.ts
e2e/tests/LoggedOut/blog.e2e.spec.ts
e2e/tests/LoggedOut/browse.e2e.spec.ts
e2e/tests/LoggedOut/inaccessiblePages.e2e.spec.ts
e2e/tests/LoggedOut/livePublication.e2e.spec.ts
e2e/tests/LoggedOut/profile.e2e.spec.ts
e2e/tests/LoggedOut/search.e2e.spec.ts
e2e/tests/LoggedOut/staticPages.e2e.spec.ts
e2e/tests/helpers.ts
e2e/tests/setup/login.setup.ts

The purpose of this PR was to speed up our tests by providing a storage file where the tests are being run that individual tests can read and use to authenticate their requests, removing the need to carry out the full log in process in each test that requires being logged in.
Although this PR will show a lot of changes there are basically only a few things being changed, but they affected the tests in lots of places.
- Instead of logging in, tests now use the new getPageAsUser helper.
- A baseUrl has been defined, so we no longer have to use a constant defined in helpers for the base URL. We can use relative paths for navigation instead.
- In publish.e2e.spec.ts, new functions have been made to standardise repeated behaviour and cut code duplication:
- requestApproval
- …

OC-768: Create global log in set up script for end to end tests

---

infra/create-app/int.tfvars

The purpose of this PR was to use a cheaper instance type for RDS on int because our resource usage is very low and we should try to keep costs down.
Note: this has already been applied.
---
Int environment's RDS is changed from db.m5.large to db.t4g.medium.
---

OC-787: Reduce RDS size on int

---

.github/workflows/api-build.yml
.github/workflows/api-tests.yml
.github/workflows/ui-tasks.yml
README.md

The purpose of this PR was to address warnings that are showing up telling us to update our github actions to stop using out of date versions of nodeJS. We should update the following wherever we use them:
- actions/checkout (to v4)
- actions/setup-node (to v4)
---
- We are using v4 of the "checkout" and "setup-node" github actions
- The warnings shown relating to this no longer appear
---
---
---
This is the output of the API and UI tasks run just before this change (note warnings):
And on the task run triggered by pushing this update, with no warnings:

OC-786: Use newer versions of github actions

---

api/package-lock.json

The purpose of this PR was to address a vulnerability with the ip package flagged by Snyk: https://security.snyk.io/vuln/SNYK-JS-IP-6240864
In order to fix it I had to run npm audit fix as suggested here: https://github.com/puppeteer/puppeteer/issues/11884. This also made some updates to other packages.
---
We no longer use the ip package at a vulnerable version (1.1.8 or before)
---
---
API
E2E

OC-821: Fix puppeteer dependency vulnerability

---

api/package-lock.json
api/package.json
api/src/lib/helpers.ts
e2e/tests/setup/login.setup.ts
ui/src/lib/cookies.ts
ui/src/lib/helpers.tsx
ui/tsconfig.alias.json

The purpose of this PR was to put in place XSS mitigations for the main text field. This includes:
- Setting the "SameSite" flag on cookies to "Strict" to help prevent these being misused
- Sanitizing the HTML that is saved to the main text field using OWASP's recommended library, DOM Purify
---
- Cookies are set with "SameSite" = "Strict"
- HTML input is sanitized against XSS attacks
---
---
API
UI
E2E
---
Existing HTML editor features still work, including code blocks containg code that would be filtered out by DOMPurify

OC-822: XSS mitigations for main text field

---

ui/src/pages/faq.tsx
ui/src/pages/user-terms.tsx

The purpose of this PR was to update the copy on the FAQ page.
In addition to this I saw some hydration errors when viewing the user terms page so have made some changes on it to prevent those.
---
1. FAQ page copy updated to include copy from attached word doc
2. Side nav bar updated with:
2.1. A new entry for “Who runs Octopus”
2.2. “Why record your research on Octopus?” changed to “Why publish my research on Octopus?”
2.3. “How to I record my work to Octopus” changed to “How do I publish my work on Octopus”
2.4. “What about copyright?” changed to “Which copyright license is used for Octopus publication?”
2.5. “Won’t people steal my ideas/data if I publish it?” changed to “Will people steal my idea/data if I publish it?”
2.6. “Why would I write a public review?” changed to “Why would I …

OC-809: New copy for FAQ page

---

infra/modules/elasticsearch/main.tf
infra/modules/postgres/main.tf

The purpose of this PR was to merge in some terraform code which has already been applied to int & production environments as part of an urgent change. This resource type is safer because it doesn't write the result in output files.
---
N/A - not in jira
---

Use random_password instead of random_string

---

api/src/components/publication/service.ts
api/src/lib/interface.ts
e2e/playwright.config.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
ui/src/lib/interfaces.ts
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to give users a way to know which publication a Peer Review is reviewing. This is to be done by adding a banner to the peer review's page with information about the reviewed publication.
---
- On a peer review page that reviews the latest version of a publication, a banner is present with the text “This is a peer review of the latest version of the following publication: <publication title>”, where the publication title is a link to the specific version of the parent publication that the peer review relates to
- On a peer review page that reviews an older version of a publication, a banner is present with the text “This is a peer review of version <version #> of the following publication: <publication title>”, where the publication title is a link to the …

OC-800: Link back to parent publication from peer review

---

infra/create-app/prod.tfvars

The purpose of this PR was to change the instance type of our prod RDS database to something cheaper.
This has been deployed to prod already.
---
- Prod RDS is a db.t4g.medium instance type
---
---
N/A
---
N/A

OC-815: Reduce RDS size on prod

---

api/src/components/publicationVersion/controller.ts
api/src/components/publicationVersion/service.ts
api/src/lib/helpers.ts

The purpose of this PR was to avoid minting versioned DOIs for peer reviews. As a user, I have no need of a version-specific DOI for peer reviews, as there will only ever be 1 version.
---
- Peer reviews only ever have a versionless DOI. No versioned DOI is minted
- On the peer review publication page:
- The “This version” DOI heading is not present
- The “DOI (All versions)” heading just reads “DOI”
---
---
API
E2E

OC-830: Avoid minting versioned DOIs for peer reviews

---

ui/src/components/FunderForm/index.tsx

The purpose of this PR was to avoid showing error banners to users unless they refer to a currently unresolved issue. In the funder form, the grant ID error banners, informing me that I have attempted to enter a duplicate funder, duplicate grant ID or improperly formatted funder should disappear when the user modifies the text in the ROR ID, grant ID, or link fields, as changing any of these fields has the potential to resolve the error (which would reappear on submit, if applicable).
---
- If either of these error messages are present:
- “This funder already exists on this publication version”
- “This funder and grant identifier already exist on this publication version.”
- And the user edits any of these fields:
- ROR ID
- Grant ID
- Link
- The error message is cleared
---
---
UI
E2E

OC-831: Make grant ID error banners hide after successful input

---

infra/modules/s3/pdf-processing-lambda-src/index.js

The purpose of this PR was to switch our pub router integration to hit the notification endpoint instead of the validation one.
The main change was to the URL we hit but this also includes some changes to deal with the response appropriately.
---
- Notifications sent to pubrouter use the /notification endpoint https://github.com/jisc-services/Public-Documentation/blob/master/PublicationsRouter/api/v4/Send.md#notification-endpoints
---
---
N/A
---
N/A

OC-840: Switch pubrouter to using /notification

---

api/src/components/publication/service.ts
api/src/lib/interface.ts
e2e/tests/setup/login.setup.ts
ui/src/__tests__/components/Publication/SidebarCard/General.test.tsx
ui/src/__tests__/components/Publication/SimpleResult.test.tsx
ui/src/__tests__/testUtils/index.tsx
ui/src/components/Publication/SidebarCard/General/index.tsx
ui/src/layouts/BuildPublication.tsx
ui/src/lib/interfaces.ts
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to satisfy the following user story:
As a peer reviewer, I need to be sure that my peer review will be displayed against the content I reviewed. I also should not have my peer review buried when new versions are published - it should still be visible against later versions, but should clearly indicate which version it was originally made against.
---
- New peer reviews can only be created against to the latest live version of a publication
- If a new version is published whilst a user has already started writing a peer review, a banner is present at the top of the edit screen (on all tabs within), reading “A new version of the publication you are reviewing has been released since you started writing this peer review. Your review will be recorded against the …

OC-390: Indicating peer review version on the front end

---

ui/src/pages/about.tsx
ui/src/pages/get-involved.tsx
ui/src/pages/index.tsx
ui/src/pages/user-terms.tsx

The purpose of this PR was to change the content on the home page so that users can see a quick and easy to understand summary of what Octopus is when they visit the site for the first time.
---
- New copy is present on the front page:
- A heading of “Free, fast and fair” in large bold text
- Below the heading, text is present reading (with linebreaks):
- The place for researchers to publish their work in full detail. Funded by UKRI – the UK government research funder.
- Octopus is a free scholarly publication platform designed to make it easier to share work of all kinds. A place for open peer review, quality assessment, and collaboration.
- Work on Octopus is not published as ‘papers’ or ‘monographs’ but in smaller units which are linked together.
- To see an example chain of Octopus …

OC-837: New front page text

---

api/package-lock.json
api/package.json
ui/src/components/Publication/Creation/LinkedItems/LinkedPublicationsCombobox.tsx

The purpose of this PR was to fix a couple of issues preventing deployment after the merge of #624 :
- Prisma CLI package was in package-lock but not package.json, and the version didn't match the client version, causing a warning
- A whitespace difference found its way into main branch that prettier is flagging as an issue

Corrections to OC-820

---

api/serverless.yml

Prisma needs to be excluded from the serverless webpack build, otherwise an error happens on deploy.
This isn't an immediate blocker because we can correct it ad-hoc at deployment time, but needs to be in the codebase.

Further correction to OC-820

---

ui/src/components/Publication/EngagementCounts/index.tsx
ui/src/components/Publication/SimpleResult/index.tsx
ui/src/pages/authors/[id]/index.tsx

The purpose of this PR was to address 3 issues found when testing OC-820:
- Engagement counts aren't shown in the publications list on the public user page
- Engagement counts could line up right next to the View button on the "my account" page
- The SVG titles of the icons are not read out by screen readers
---
The 3 issues listed above are fixed.
---

OC-820: Corrections following testing

---

api/Dockerfile

The purpose of this PR was to change the docker image we use for our API test github action because the current one has an [issue](https://security.snyk.io/vuln/SNYK-DEBIAN12-ZLIB-6008963) flagged as a critical issue by Snyk.
This is the snyk page for the new image used in this PR: https://snyk.io/test/docker/node%3A18-alpine
---
- The docker image we use in /api/Dockerfile does not have any issues flagged as critical by Snyk.
---
---
Results of API tests run locally on this container:

OC-850: Resolve critical security issue in API docker image

---

api/prisma/seeds/users.ts
api/src/components/authorization/__tests__/authorization.test.ts
api/src/components/authorization/controller.ts
api/src/components/authorization/routes.ts
api/src/components/crosslink/routes.ts
api/src/components/user/service.ts
api/src/middleware/authentication.ts
ui/src/__tests__/pages/verify.test.tsx
ui/src/components/Avatar/index.tsx
ui/src/components/Header/index.tsx
ui/src/components/Nav/index.tsx
ui/src/components/Publication/SidebarCard/Actions/index.tsx
ui/src/config/urls.ts
ui/src/lib/helpers.tsx
ui/src/pages/authors/[id]/index.tsx
ui/src/pages/publications/[id]/versions/[versionId].tsx
ui/src/pages/verify.tsx

The purpose of this PR was to ensure that users have a value for firstName and lastName before they are allowed to make actions that associate them with data in Octopus. Users can set visibility of their name in ORCiD to "only me", which means octopus can't access it.
---
- When a user red flags, creates a new publication, publishes, confirms involvement, or approves, if Octopus cannot detect a name for that user, the request is rejected
- Every time a user logs in, their current name is saved against their Octopus account if it can be found on their ORCiD profile.
- If Octopus is unable to find a name from the user’s ORCiD profile in future, the saved name is used instead.
- For example, for displaying on author lists, their profile page, red flag records, data sent to datacite, etc.
- …

OC-789: Require name visibility to create publications, publish, confirm involvement and red flag

---

ui/src/components/Header/index.tsx

The purpose of this PR was to add an additional case to the "missing information" messages we display in the header. In the case that the user has both of the following statements apply to them:
- They have no first or last name
- They have not confirmed their email address
A message will be shown that explains both of these situations at once, and the actions they should take in order.
---
If a logged in user has no first or last name against their account and has no confirmed email address, this message is shown in a banner in the site header:
- 'Please set your name to be visible on your ORCiD profile, then return to Octopus to verify your email to be able to publish content.'

add combined message in header if user has no names or confirmed email

---

ui/next.config.js

The purpose of this PR was to send a Content Security Policy to the Octopus front end application, as an added layer of security that helps to detect and mitigate certain types of attacks, including Cross Site Scripting (XSS) and data injection attacks.
---
- A CSP response header is sent on Octopus and is restrictive as we can make it without breaking parts of the application.
---
---
E2E:

OC-324: Implement Content Security Policy (CSP)

---

api/src/components/publication/controller.ts

The purpose of this PR was to cover an issue where field values could be provided when creating a publication, and weren't being validated or sanitized correctly before being saved. The scope of this work was to address this for the content field, which takes HTML.
---
- Content sent to Octopus using the create publication endpoint’s “content” field is sanitised
---
---
API
E2E

OC-847: Sanitise input for create publication endpoint

---

api/package-lock.json
api/package.json
api/serverless.yml

The purpose of this PR was to explore ways of changing our use of the serverless framework to avoid running into the CloudFormation limit of 500 resources per application (or stack).
In this investigation I learned of quite a simple way to automatically spread resources across nested cloudformation stacks using a serverless plugin. It's a good stop gap solution for the time being, while we might consider re-architecting octopus to consist of micro services in the longer term.
A test deploy has successfully run on the int environment, which required removing the old stack and creating this new one afresh.
---
- A workable way forward to avoid the cloudformation resource limit is found.
---
---
N/A
---
Relevant selection from deployment output:

OC-842: Strategy to avoid cloudformation resource limit

---

ui/next.config.js

This is a quick pull request to allow matomo scripts in our content security policy as they are currently being blocked.

Add matomo to list of allowed script sources

---

ui/next.config.js

This is a follow-up to #645 after it emerged that matomo needs to be added to the connect-src directive as well.

OC-864: Add matomo url to connect-src

---

api/nodemon.json
api/serverless-config-default.yml
api/serverless-config-deploy.yml
api/serverless-offline.yml
api/serverless.yml
infra/README.md
infra/create-app/new-int.tfvars

The purpose of this PR was to try to deploy our serverless application to the separate int account and do what we can to get it working in a reasonable timeframe. We now have a working API in the new environment: https://new-int.api.octopus.ac/v1/
This was enabled by the code changes in this PR and some manual changes outside of the code:
- Remove resources labelled "new-prod" from account now that we have decided to move the int account instead.
- Provision as much as we can of the terraform infrastructure with the workspace "new-int" in the new account.
- This is everything apart from 4 SES identities that can't be deployed without an error (we already knew this was an issue).
- Run a serverless deploy with the "new-int" stage.
- This required creating a new certificate in certificate …

OC-503: Spike: run serverless on int account

---

ui/src/components/IconButton/index.tsx
ui/src/layouts/BuildPublication.tsx
ui/src/pages/publications/[id]/edit.tsx

The purpose of this PR was to reposition focus at the top of the editing section when the user hits one of the lower prev/next buttons on the publication editing page. Up to now, focus remained in the same place, so users would have to backtrack through the new section entirely to get to the start of it.
Experimented with a few things, but on balance felt that changing focus to the equivalent button in the higher navigation area made the most sense, in combination with the message displayed in the aria-live region. The element is already focusable and the navigation immediately precedes the content area that has changed.
---
- After using the “Next” and “Previous” options at the bottom of each tab of the edit page, focus moves to the top of the newly displayed tab area
- An ARIA polite …

OC-813: Avoiding repeated back-navigation when using next/previous options

---

api/package-lock.json
api/package.json
api/serverless.yml
api/src/components/publicationVersion/service.ts
api/src/components/sqs/handler.ts

The purpose of this PR was to investigate a [publication](https://int.octopus.ac/publications/ysjc-sc09/versions/latest) on int which had failed to generate a PDF.
There is an (almost) identical [publication](https://www.octopus.ac/publications/nv07-6x75/versions/latest) on prod that had its PDF generate successfully.
The PDF is now generated: https://s3.eu-west-1.amazonaws.com/science-octopus-publishing-pdfs-int/ysjc-sc09.pdf
---
- Successfully generate the PDF that has been failing
- Set up extra logging for PDF generation
- Set up slack notifications for when PDF generation fails
---
---
API
E2E
---

OC-866: PDF failed to generate

---

.github/workflows/api-tests.yml
api/docker-compose.yml
api/src/components/verification/__tests__/confirmCode.test.ts
api/src/components/verification/__tests__/requestCode.test.ts
api/src/lib/testUtils.ts
docker-compose.yml
e2e/.env.example
e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/helpers.ts

The purpose of this PR was to make changes to the docker-compose file to stop our use of outdated docker images that have security vulnerabilities.
This is mostly using later image versions but two changes were a bit different:
- Mailhog was swapped out for a similar application called Mailpit which was pretty much like for like. Mailpit is actively updated while mailhog hadn't been updated for some time.
- Adminer was removed because its latest docker image had vulnerabilities and a similar utility can be got from running `npx prisma studio` in the /api directory.
---
- Update vulnerable / outdated software  / docker images in use on the docker containers.
---
---
E2E

OC-867: Secure docker-compose file

---

api/prisma/migrations/20240509091139_crosslink_score/migration.sql
api/prisma/schema.prisma
api/prisma/seeds/publications.ts
api/prisma/seeds/publicationsDevSeedData.ts
api/src/components/crosslink/__tests__/getPublicationCrosslinks.test.ts
api/src/components/crosslink/controller.ts
api/src/components/crosslink/routes.ts
api/src/components/crosslink/schema/getPublicationCrosslinks.ts
api/src/components/crosslink/service.ts
api/src/lib/interface.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/PageModel.ts
ui/src/__tests__/components/AccordionSection.test.tsx
ui/src/__tests__/components/Publication/RelatedPublications.test.tsx
ui/src/__tests__/components/Publication/RelatedPublications/Card.test.tsx
ui/src/__tests__/components/Publication/RelatedPublications/Result.test.tsx
ui/src/__tests__/testUtils/index.tsx
ui/src/components/Alert/index.tsx
ui/src/components/Modal/index.tsx
ui/src/components/Publication/RelatedPublications/Modal/index.tsx
ui/src/components/Publication/RelatedPublications/Result/index.tsx
ui/src/components/Publication/RelatedPublications/index.tsx
ui/src/components/Publication/SearchResult/index.tsx
ui/src/components/index.tsx
ui/src/config/endpoints.ts
ui/src/lib/interfaces.ts
ui/src/pages/publications/[id]/versions/[versionId].tsx
ui/src/pages/search/publications/index.tsx

The purpose of this PR was to give users a way of viewing all the crosslinks associated with a publication, further to the related publications sidebar which is capped at showing 5 links.
---
- Whilst viewing a publication page and there are more than 5 suggested links, a button to “Show All” is present at the bottom of the “Related publications” area, opening the “Related Content” modal. 
- The “Related Content” modal shows a list of each publication that has been suggested for linking with this publication, including title, publication date and first author.
- A search control is present at the top of the modal to search user suggested links by publication title
- Above the publication list, the text “Sort by” is present, with options available to sort the list by “Most recent” and …

OC-771 - Displaying all cross links

---

ui/src/components/Modal/index.tsx
ui/src/components/Publication/RelatedPublications/Modal/index.tsx

The purpose of this PR was to fix an issue that arose from OC-771 where modals unrelated to the item itself changed style due to the changes in the item. This PR makes those changes only applicable if a "wide" prop is passed to the Modal component. The default styling will remain as it used to be.
---
- Publications other than the related publications modal retain their width and button widths from before OC-771.
---
---
Not run.
---
Before/after with modal unrelated to OC-771:
Before/after with the modal from OC-771 (to demonstrate slight change to button width that was worked into this PR):

OC-771 fix: make wide modal styling opt-in

---

api/prisma/seeds/publicationsDevSeedData.ts
api/src/components/crosslink/service.ts
api/src/components/user/__tests__/getUsers.test.ts
api/src/components/user/service.ts
ui/src/components/Publication/RelatedPublications/Modal/index.tsx
ui/src/components/Publication/RelatedPublications/Result/index.tsx
ui/src/pages/blog/index.tsx
ui/src/pages/search/authors/index.tsx
ui/src/pages/search/publications/index.tsx
ui/src/pages/search/topics/index.tsx

The purpose of this PR was to address feedback on 771 and change the way the filtering works in the "display all crosslinks" modal so that the form doesn't need to be submitted, and results appear as you type.
---

OC-771 fix: make search auto update

---

api/docs/api.yml
ui/src/components/Nav/index.tsx

The purpose of this PR was to give users a way to get in touch to request an API key.
---
- Text is present at the top of the API documentation reading “An API key is required for many of the API’s operations. To request a unique API key, please send an email to [help@jisc.ac.uk](mailto:help@jisc.ac.uk) from the address you are signed up to Octopus with, including the subject line “Octopus API key request”
- Where [help@jisc.ac.uk](mailto:help@jisc.ac.uk) is a mailto “mailto:help@jisc.ac.uk?subject=Octopus API key request”
- A link is present at the bottom of the “How To” dropdown reading “API Documentation” that links to https://www.octopus.ac/documentation/api
---
---

OC-862: Requesting API keys

---

api/README.md
api/package-lock.json
api/package.json
e2e/tests/PageModel.ts

The purpose of this PR was to address the fact that the copy-webpack-plugin package has vulnerabilities in its subdependencies. The way we use it is quite simple but it actually turned out to be difficult to do without this package, so instead this PR overrides the semver for its subdependency "micromatch". This means that the versions of the affected packages will be newer than the vulnerable ones.
Added a section to the API readme explaining why the dependency override was added so it can be removed if it ever becomes redundant.
---
- Either copy-webpack-plugin is removed (with PDF generation still working and styled correctly), or the vulnerabilities in its subdependencies are addressed.
---
---
E2E
API

OC-873: Remove or replace copy-webpack-plugin from API

---

ui/src/components/Publication/RelatedPublications/Modal/index.tsx
ui/src/components/Publication/RelatedPublications/Result/index.tsx
ui/src/components/Publication/RelatedPublications/index.tsx

The purpose of this PR was to fix some issues observed with the "View All" related publications modal.
- The modal will resize rapidly as it adjusts to display results for my search term.
- To fix this, the modal should not resize when the number of results changes.
- The search term, sort order, results etc. are retained when the modal is closed and re-opened.
- To fix this, the modal's state should be reset when it is re-opened.
---
- The all cross-links modal always displays with a height equivalent to if it were showing 5 search results, even if less are visible.
- Upon re-opening the all cross-links modal, any previously entered search term is disregarded and the full list of cross links is displayed.
---
---
UI
E2E
---
Modal retains size when showing fewer results

OC-876: Cross link show all improvements

---

api/src/components/flag/controller.ts
api/src/components/publicationVersion/__tests__/updatePublicationVersion.test.ts
api/src/lib/helpers.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts

The purpose of this PR was to address the fact that text alignment is not saved on the main text editor. When text is centred or right-aligned, this state is not retained upon saving, meaning the text appears as (default) left aligned when previewing, publishing or revisiting the edit page.
This has been happening because of our long-standing HTML sanitisation code. This takes a simple approach of removing all classes and styles from HTML. Now that we also use DOMpurify in the same place to achieve the same ends, we can safely remove our previous method. This way, intentional / safe styles, like the one that applies text direction, can be preserved.
---
Publication content can be saved with centre and right aligned text added using the UI's text editor.
---
---
API
E2E
---

OC-853: Text alignment not retained on main text editor

---

ui/src/components/Publication/RelatedPublications/index.tsx

The purpose of this PR was to stop the related publications sidebar being shown on deployed environments unless crosslinks exist on the publication being viewed. This is a soft way of keeping crosslinking unavailable on prod until the full feature has been developed.
Without this fix, the "Suggest a link" button would be available and people could start using the feature without proper guidance.
---
On int and prod, the Related Publications sidebar does not show if the publication being viewed does not have any crosslinks associated to it.
---

OC-772 fix: Hide related publications sidebar on deployed environments

---

ui/src/config/values.ts

The purpose of this PR was to ensure that bold text is the same colour as normal weight text in the publication content area.
Note this only affected dark mode.
---
- Bold text should remain the same colour as other text instead of having any custom colouring added without the user requesting it.
---
---
UI
E2E
---
Before
After

OC-852: Bold text turns blue on publication page

---

api/package-lock.json
api/package.json
api/src/components/publicationVersion/service.ts
e2e/package-lock.json
e2e/package.json
e2e/tests/LoggedIn/livePublication.e2e.spec.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/helpers.ts

The purpose of this PR was to address a vulnerability snyk flagged with the "ws" package that is introduced to octopus through other dependencies.
---
- ws is at at least version 8.17.1
---
---
API
E2E

OC-890: High vulnerability in API package "ws"

---

api/prisma/createOrganisationalAccounts.ts
api/src/components/user/__tests__/createOrganisationalAccounts.test.ts
api/src/components/user/__tests__/updateOrganisationalAccount.test.ts
api/src/components/user/controller.ts
api/src/lib/interface.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts

The purpose of this PR was to make some changes to the script and functions involved in creating organisational accounts to facilitate adding some government department accounts related to the ARI DB integration.
This was mainly work to allow default topics to be set on creation, and changes to support topic IDs for int and prod environments in the input data.
---
- Accounts exist for all 21 ARI departments (see  spreadsheet ari_departments.xlsx  )
- The script will be run with supplied data after this code is approved.
---
---
API
E2E
---
Government department account inserted successfully on local environment

OC-887: Create accounts for ARI departments

---

ui/src/pages/accessibility.tsx

The purpose of this PR was to update the content of the accessibility statement at /accessibility.
---
- Replace the content of the /accessibility page with the attached word doc (in Jira)
- Retain 
“Content modified from:
[GOV.UK accessibility statement](https://www.gov.uk/help/accessibility-statement)
Used through the:
[Open Government Licence v3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/)”
at the bottom of the page
---
---
UI

OC-892: A11Y Statement update

---

api/src/components/publication/service.ts
api/src/components/publicationVersion/service.ts

The purpose of this PR was to skip sending a message to the PDF generation queue when a publication is published directly. The PDF will still be generated if requested, just not automatically as it would be if triggered by the queue. PDF generation triggers a message sending to publications router with details from the PDF, but there's not a need for this for ARI publications at present.
---
- Directly published publications don't hit the PDF generation queue.

OC-884 fix: Skip automatic PDF generation for direct publishes

---

api/prisma/seeds/local/unitTesting/publications.ts
api/scripts/fullAriImport.ts
api/serverless-config-default.yml
api/serverless.yml
api/src/components/integrations/service.ts
api/src/components/publicationVersion/service.ts
api/src/lib/__tests__/helpers.test.ts
api/src/lib/helpers.ts
api/src/lib/integrations/__tests__/ari.test.ts
api/src/lib/integrations/ariUtils.ts

The purpose of this PR was to add a way for octopus to stay up to date with ARIs from the ARI DB, including new ARIs, and updates to existing ones. The function hits ARI DB’s API weekly to detect changes and newly added records, and triggers creation/updating of ARIs on Octopus as needed.
Tested function locally by manual invocation and retested full ari import script since I changed that too.
- Deviated from the ACs on how we stop the job.
- It seemed more robust to check that there are 5 unchanged ARIs in a row (our original plan) before stopping.
- Going by the dateUpdated value is risky because we only have the most recent "updatedAt" value in octopus to go by. This would be slightly later than the time the last import began, so we risk missing ARIs that were updated in between our …

OC-885: Weekly ARI ingest

---

api/serverless-config-default.yml

The purpose of this PR was to fix an issue with #681 where the cron expression in the serverless function definition wasn't valid so it wouldn't deploy properly.
---
Octopus deploys to int without an error.
---
---

OC-885 fix: make cron expression valid

---

api/serverless-config-default.yml

The purpose of this PR was to make a quick fix that overrides the default lambda timeout of 30 seconds for our ARI import lambda to the maximum of 900 seconds because it timed out on its first test run. This is really a placeholder until we can build the solution in ECS.
---
ARI import lambda has the maximum timeout of 15 minutes.
---

Increase timeout for ari import lambda

---

api/src/components/publication/service.ts
api/src/components/publicationVersion/__tests__/createPublicationVersion.test.ts
api/src/components/publicationVersion/controller.ts
api/src/components/publicationVersion/service.ts
api/src/lib/integrations/__tests__/ari.test.ts
api/src/lib/integrations/ariUtils.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
ui/src/components/Publication/SidebarCard/General/index.tsx
ui/src/lib/helpers.tsx
ui/src/lib/interfaces.ts
ui/src/lib/types.ts
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to ensure that, in relation to ARI publications (which only take one version), users do not see a versioned DOI if only one version will ever exist. They should be informed of updates to the DOI via the publication date.
---
- DOIs for publications with a source of “ARI” are configured like peer reviews, with only a single DOI used instead of the pair of versionless/versioned DOIs
- The UI for ARIs is updated to not include versioning-related UI such as the version dropdown
- When updated, the “publication date” on ARIs are updated to the current date
---
---
E2E
API
UI
---
Versioned publication with version accordion, and mention of versions in sidebar
ARI, without these features

OC-909: Configure ARIs to display a single DOI

---

api/prisma/migrations/20240911122447_ingest_logs_table/migration.sql
api/prisma/migrations/20240911151436_remove_old_bookmark_model/migration.sql
api/prisma/schema.prisma
api/prisma/seeds/index.ts
api/prisma/seeds/local/unitTesting/ingestLogs.ts
api/src/components/ingestLog/__tests__/ingestLog.test.ts
api/src/components/ingestLog/service.ts
api/src/components/integrations/service.ts
api/src/components/publication/service.ts
api/src/components/publicationVersion/service.ts
api/src/lib/integrations/ariUtils.ts
api/src/lib/testUtils.ts
api/tsconfig.json
e2e/tests/LoggedIn/search.e2e.spec.ts

The purpose of this PR was to have a more reliable way of knowing when to stop our incremental ARI ingest job. Sometimes, real changes on the ARI side could be detected as not changed on the octopus side because they wouldn't result in changes to the octopus publication. Thus this item changes the criteria for stopping the job when:
- 5 ARIs in a row are found that don't present changes to what we have in octopus (previous condition)
- the job has encountered an ARI with dateUpdated before the start time of the most recent previous job (new condition)
- N.B. the data is sorted by dateUpdated
This is achieved by adding an IngestLog model to the database where we can store data on ingest jobs such as their start and end times and check that on later runs.
In addition, this PR makes these …

OC-910: Update weekly ingest to store and check dates

---

api/src/components/integrations/service.ts

This is a small fix PR to stop an if check from repeatedly passing and repeating a log message that was only intended to appear once.

OC-910 fix: stop log message repeating unnecessarily

---

infra/modules/bastion/main.tf

This is a simple PR to revert a change that should not have been made. I thought we no longer needed a public IP address to use SSM sessions on our bastion servers, but we do.

Set bastions to have a public IP address again

---

api/README.md
api/package-lock.json
api/package.json

The purpose of this PR was to address a vulnerability alerted to us by Snyk in the micromatch package.
It's included in the copy-webpack-plugin. I spent some time trying to see if we could stop using this plugin but I don't think we can. We need font+image files to be present in the build so that we can use fs.readFileSync on them when generating PDFs, and webpack doesn't seem to be able to do this by itself without the copy plugin (because the assets aren't included as import/require statements for webpack to detect). So it has been solved with a package.json override.
PDF generation still works fine after the update.
---
- micromatch is installed at >= 4.0.8
---
---
E2E
API

OC-918: Fix high severity vulnerability in micromatch

---

e2e/playwright.config.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
ui/next-env.d.ts
ui/package-lock.json
ui/package.json

The purpose of this PR was to update nextJS in order to remediate a security issue reported by Snyk.
I cherry-picked a commit from another pending PR to get end to end tests to run, so that's why this presents changes to those files.
---
Octopus uses NextJS 14.2.10 or higher.
---
---
UI
E2E

OC-921: High severity security issue in NextJS

---

api/src/components/user/service.ts
e2e/tests/LoggedIn/livePublication.e2e.spec.ts
e2e/tests/LoggedIn/topic.e2e.spec.ts
e2e/tests/PageModel.ts

The purpose of this PR was to fix a bug where one user's account page could show another user's publications if they shared an email address.
This was happening because the "get user publications" endpoint included a condition to get publications with a coauthor sharing the user's email address (indicating that they had been added, but not confirmed themselves, as a coauthor on the publication).
This can't occur with general users, due to details coming from orcid which uses unique email addresses, but can happen with organisational ones.
This condition is only relevant when showing users their own publications on the "my account" page. This fix ensures that it will only be applied on requests from there (as far as the UI is concerned) and narrows down the criteria as much as possible …

OC-912: Duplicate account emails cause author pages to show pubs from other accs

---

api/serverless-config-default.yml
api/src/components/integration/__tests__/ari.test.ts
api/src/components/integration/ariUtils.ts
api/src/components/integration/controller.ts
api/src/components/integration/routes.ts
api/src/components/integration/schema/incrementalAriIngestHttp.ts
api/src/components/integration/schema/index.ts
api/src/components/integration/service.ts
api/src/lib/email.ts

The purpose of this PR was to add a dry run feature to the ARI integration. In order to test the ARI integration, and to avoid the risk of the ingest timing out if a high number of ARIs need to be updated/created, a dry run feature is needed to check how the ingest will behave before each run.
---
- The endpoint to run the ingest operation on int or prod now contains a dry run parameter
- Enabling this option will cause the ingest to run without actually making any changes, including:
- No new ARIs are created, nor any updates to existing ARIs
- No updates to the log of previous ingests that was created as part of OC-910
- The email (see OC-888) is still returned upon completion of the operation, including stats for what would’ve been created
---
---
E2E
API
---
Note that the double space …

OC-911: ARI ingest dry runs

---

infra/modules/ses/main.tf

The purpose of this PR was to update the runtime of our mail functions which have been using python3.8, which goes out of support on 14/10/24.
This has already been deployed.
---
Mail forwarding lambda functions are using python 3.12 runtime and still work.
---
---
Confirmed that mail is still received via these forwarding functions:

OC-902: Update mail lambda functions to use python 3.12

---

api/prisma/schema.prisma

The purpose of this PR was to change the binary targets for prisma. It seems that the nodeJS 20 runtime environment for lambda requires a newer target for prisma to generate client code.

OC-899-fix: update prisma binary target

---

api/docs/api.yml
api/src/components/coauthor/__tests__/getCoAuthors.test.ts
api/src/components/coauthor/controller.ts
api/src/components/publicationVersion/controller.ts

The purpose of this PR was to ensure that coauthors cannot see the emails of other coauthors from API responses (corresponding authors are allowed to see these however).
---
Co-authors are not sent the email addresses of other co-authors via the API.
---
---
E2E
API
---
In all these examples a third author is being viewed separate to the two making the requests.
Corresponding author sees emails in response to API call made on publication page
Coauthor does not
Corresponding author can get emails from calling getCoauthors API function directly
Coauthor cannot

OC-930: Hide co-author email addresses from other co-authors

---

api/prisma/seeds/local/dev/topicMappings.ts

The purpose of this PR was to correct typos in two topic names that are failing to match on ARI imports.
This corrects the seed data - separately, the mappings have been updated in the int and prod DBs.
---
The topic mappings 'creditand debt' and 'industrialaccident and incident' have been corrected to 'credit and debt' / 'industrial accident and incident'.

OC-934: Add spaces to topics failing to match

---

api/src/components/user/service.ts
ui/src/components/Publication/SimpleResult/index.tsx

The purpose of this PR was to stop including emails in the response of the getUserPublications endpoint. We don't need them for the tasks the endpoint is called to do.
---
Email addresses are not included in the response to the getUserPublications endpoint.
---
---
API
E2E
---
Response on public author page
Response on my account page

OC-941: Stop including emails in user publications response

---

api/.env.example
api/docker-compose.yml
api/scripts/fullAriImport.ts
api/serverless-offline.yml
api/serverless.yml
api/src/components/integration/README.md
api/src/components/integration/ariUtils.ts
api/src/components/integration/service.ts

Government departments want to display high quality ARIs to ensure they can engage with the research community effectively. I need ministerial sign-off to change existing (outdated) ARIs, so I may take a while to update them. This means on octopus we have to be able to import ARIs from some departments, but not others.
This area being changed (which ARIs are imported) isn't covered in tests so these haven't been run, but it has been tested locally.
---
- A whitelist exists of government departments that have opted in to the ARI integration
- For both the initial ingest, and the weekly updates (endpoint), if the department for a given ARI is not on the whitelist, the record is skipped
- Skipping records does not contribute towards the count of 5 records before stopping the ingest, nor …

OC-932: Deploy ARI integration for specific departments

---

ui/src/__tests__/components/Publication/RelatedPublications.test.tsx
ui/src/components/Button/index.tsx
ui/src/components/Publication/RelatedPublications/index.tsx
ui/src/pages/faq.tsx

As a user, I should have an explanation of what cross links are and how to use them.
---
- In the suggested links area:
- Whilst logged in, a link is present below the area title, above the list of publications, displayed via link style text reading “What is this?” and an “info” type icon pointing to the “How are related publications identified?” section of the FAQ
- The FAQ includes a new “How are related publications identified?” section. Copy as follows: 
```
How are related publications identified?
To avoid bias, Octopus does not use any sort of algorithm to identify related publications. Instead, whilst viewing a publication that has already been published, the related publications area displays publications that have been identified by readers as being related to the one currently …
```

OC-851: Explanatory hotspot for cross links

---

api/src/components/publicationVersion/service.ts

Currently, ARIs are uploaded to datacite with an individual author type. They should be organisational authors instead. Whilst the “Creator” field allows organisational details to be entered in the same manner as an individual’s, the “Contributor” area does not allow this. Instead, the “nameType” should be set to “Organisational”.
---
- When minting a DOI for an ARI, the “nameType” value within the Contributor section is set as “Organizational” (US spelling) instead of “Personal”.
---
---
API
E2E
---
XML metadata of an ARI publication on datacite before the change:
And after:

OC-939: Ensure ARIs have organisational authors

---

api/src/components/publicationVersion/service.ts
api/src/lib/interface.ts

The purpose of this PR was to make a similar change to OC-939, but on the creator part of a DOI record, where the original change was only on the contributor part.
---
The nameType for organisational users on DOI records is "Organizational", remaining "Personal" for other users.
---
---

OC-939 fix: Use organizational name type for creators too

---

e2e/tests/LoggedIn/crosslinking.e2e.spec.ts
ui/src/__tests__/components/Publication/RelatedPublications.test.tsx
ui/src/components/Publication/RelatedPublications/SuggestModal/index.tsx
ui/src/components/Publication/RelatedPublications/index.tsx
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to make 2 fixes to OC-773 (voting on crosslinks):
- If a user had an existing vote it wasn't being shown correctly
- It wasn't being set correctly in getServerSideProps
- After creating a crosslink, the list should be refetched so it is immediately shown under "Most recent" in the sidebar
- Solved using SWR mutate
---
- Pre-existing crosslink votes are shown correctly in the voting area
- After creating a crosslink, it is shown under "Most recent" in the sidebar
---

OC-773 fixes

---

e2e/tests/LoggedOut/crosslinking.e2e.spec.ts
e2e/tests/PageModel.ts
ui/src/__tests__/components/Publication/RelatedPublications.test.tsx
ui/src/components/Publication/RelatedPublications/SuggestModal/index.tsx
ui/src/components/Publication/RelatedPublications/index.tsx
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to help users to quickly view all content & functions of the suggested links feature with minimal extra navigation.
---
- The “Suggest a link” modal” is short enough to fit within the browser window on 1080p screen at 100% display scaling
- The versions, info and suggested links areas are all locked to the page rather than scrolling
- The “Show all” button is renamed to “View all”
- The “View all” button in the related publications area is visible if at least 1 link has been added
---
---
UI
E2E - IDE crashed when nearly all of them were done and I ran the rest after restarting, but the plugin lost track of the last run when it crashed... please take my word for it, they all passed!
---
AC 1 (smaller viewport height):
All other ACs - renamed button, button …

OC-955: Suggested links navigation improvements

---

e2e/tests/LoggedOut/crosslinking.e2e.spec.ts
ui/src/components/Publication/RelatedPublications/ViewAllModal/index.tsx

The purpose of this PR was to reduce the height of the view all crosslinks modal to reduce the chance that users have to scroll down to see the confirm/close buttons.
---
- The “View all” modal” only contains 4 results, and is short enough to fit within the browser window on 1080p screen at 100% display scaling
---
---
UI
E2E (relevant tests)
---
Close button is visible on a 900px high viewport

OC-948: Reduce "View All" modal height

---

ui/src/components/Publication/RelatedPublications/VotingArea/index.tsx

The purpose of this PR was to help users to be able to clearly tell whether or not they have voted on a crosslink already, and how they have voted.
---
- Voting options are displayed as “Thumbs up” and “Thumbs down” style icons instead of as carets
- Voting in favour of a suggested link causes the positive vote box to be highlighted with a green outline
- Voting against a suggested link causes the negative vote box to be highlighted with a red outline
- This outline does not conflict with the focus outline
---
---
Change not covered in tests
---

OC-949: Additional UI indication of user votes

---

api/prisma/seeds/local/dev/organisationalAccounts.ts
api/prisma/seeds/local/dev/userMappings.ts
api/scripts/fullAriImport.ts
api/src/components/integration/ariUtils.ts

The purpose of this PR was to add config for 2 new government departments that have started to publish ARIs so that we can handle them when we import ARIs.
No issues or unrecognised topics when running a full import locally.
---
- An organisational account exists for “HM Treasury (UK)”, mapped to the ARI DB organisation “HMT”, with a default topic of “Expenditures. Government spending” ([Expenditures. Government spending - Octopus | Built for Researchers](https://www.octopus.ac/topics/cllqi3mxp00p2m48wyugqhh2c) // [Expenditures. Government spending - Octopus | Built for Researchers](https://int.octopus.ac/topics/clkv6ulvw01dyl2rsjhplwtqo) )
- An organisational account exists for “HMRC (UK)”, mapped to the ARI DB organisation “HMRC”, with a default topic of “Revenue. Taxation. Internal …

OC-964: Add HMRC and HMT to ARI ingest

---

e2e/tests/PageModel.ts
e2e/tests/helpers/livePublication.ts
ui/src/components/AccordionSection/index.tsx
ui/src/components/Button/index.tsx
ui/src/components/Nav/index.tsx
ui/src/components/Publication/PublicationPage/CoAuthoringActions/index.tsx
ui/src/components/Publication/PublicationPage/HeaderActions/index.tsx
ui/src/components/Publication/RelatedPublications/index.tsx
ui/src/components/Publication/SidebarCard/Actions/index.tsx
ui/src/components/Publication/SimpleResult/index.tsx
ui/src/components/index.tsx
ui/src/config/endpoints.ts
ui/src/config/errors.ts
ui/src/config/index.ts
ui/src/layouts/BuildPublication.tsx
ui/src/lib/api.ts
ui/src/pages/about.tsx
ui/src/pages/browse.tsx
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to encourage users to publish by moving the options to contribute to a more clearly visible place that reflects their role as a primary function of the system.
While working on this, also made some more changes:
- Move baseURL to endpoints config from api config to avoid circular dependency error.
- Remove unused errors config.
- Attempt to standardise button classes a bit by introducing a variant prop.
- Fix a bug where clicking logout would cause a "Cancel rendering route" nextJS error because it attempts to follow the link and do a router.push() at the same time.
---
- The following options are no longer present in the side bar actions area: 
- “Write a linked <publication type>”
- “Write a linked review”
- “Write a linked research problem” 
- Below the …

OC-958: Move publish options to sit above title

---

ui/src/config/endpoints.ts

The purpose of this PR was to fix an issue introduced in OC-958  (#718).
When replacing the string "api." in the file it removed it from the API base URL but this didn't have an effect locally so wasn't spotted.

OC-958 fix: restore "api." that was removed with too much find and replace

---

infra/README.md
infra/create-app/main.tf
infra/create-app/provider.tf
infra/modules/cloudfront/main.tf
infra/modules/cloudfront/vars.tf

The purpose of this PR was to fix an issue where attempts to save publications with a reasonably long content field were failing. This was occurring because our cloudfront distribution sitting in front of the API gateway was rejecting any request with a body over 16KB in size, due to the managed AWS rules. It's difficult to override this in the console, so as part of this solution I have terraformed the cloudfront distribution and the "packaged" web acl you can create with it. Then I added an override for the applicable rule.
The extra provider alias is because the web ACL needs to live in the us-east-1 region.
Working fine on int environment after applying this terraform. Note: before applying to prod, the cloudfront distribution (and not the web acl) needs to be imported into the …

OC-966: Save failing on publication edits

---

infra/modules/cloudfront/main.tf

The purpose of this PR was to override an AWS WAF rule that blocks legitimate publication save requests. The HTML editor creates a table with a style attribute and the style attribute is blocked by the rule. Unfortunately there doesn't seem to be a more refined way than this to disable that, other than overriding the rule.
---
Publications with a table in their content can be saved.
---

OC-966 fix: Override AWS XSS body rule

---

api/serverless-config-default.yml

The purpose of this PR was to fix an issue where PDFs are not generating. This is because the binary to launch chromium doesn't work on arm64 architectures ([github issue](https://github.com/Sparticuz/chromium/issues/186)), which we recently started using.
This PR changes the architecture of this function while leaving others on arm64.

OC-967: PDF generation won't work on ARM lambda functions

---

ui/src/pages/author-guide.tsx
ui/src/pages/get-involved.tsx

The purpose of this PR was to make a few updates to static text and links on the site.
---
- The “Mailing list” link at the bottom of the get involved page now points to https://www.jisc.ac.uk/forms/sign-up-for-octopusac-news-and-updates
- The final sentence of the get involved page ending “…follow us on twitter” now also includes the text “or Bluesky” where “Bluesky” is a link to [Octopus.ac (@octopus-ac.bsky.social)](https://bsky.app/profile/octopus-ac.bsky.social) 
- On the author guide, please change the first sentence from “Octopus publications are different to traditional journal articles or papers.” to “Octopus publications are different from traditional journal articles or papers.” (from instead of to).
---
---
UI
E2E

OC-962: Minor copy & link updates

---

e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/LoggedOut/search.e2e.spec.ts
ui/src/pages/search/publications/index.tsx

The purpose of this PR was to fix an oversight introduced with the new Author Types search filter. The Clear Filters button does not clear this new filter.
---
- The “Clear filters” option removes any selection in the “Author types” filter.
---
---
UI
E2E

OC-981: Clear author type filter using clear filters option

---

api/src/components/publication/__tests__/createPublication.test.ts
infra/create-app/main.tf
infra/create-app/provider.tf
infra/docker/poc/Dockerfile
infra/modules/bastion/main.tf
infra/modules/codepipeline/buildspec/deploy-docker-image.yml
infra/modules/codepipeline/codebuild.tf
infra/modules/codepipeline/codepipeline.tf
infra/modules/codepipeline/s3.tf
infra/modules/codepipeline/vars.tf
infra/modules/ecr/ecr.tf
infra/modules/ecr/vars.tf
infra/modules/ecs/ecs.tf
infra/modules/ecs/iam.tf
infra/modules/ecs/outputs.tf
infra/modules/ecs/services.tf
infra/modules/ecs/tasks.tf
infra/modules/ecs/vars.tf
infra/modules/network/outputs.tf
infra/modules/oidc/main.tf
infra/modules/s3/main.tf
infra/modules/ses/main.tf

The purpose of this PR was to work a proof of concept ECS setup I made separately into octopus's codebase. The terraform code creates:
- An ECR for docker containers
- A codepipeline which builds a docker container when the source branch (int/prod) is pushed to
- An ECS service which runs a task using the latest of these docker containers
The proof of concept just logs a simple message.
There is one per environment because the idea is that this infrastructure will be used to run scripts against each environment like the ARI import script.
---
The proof of concept ECS setup can be deployed and run within octopus's environment.
---
---
Service running on int
Service running on prod

OC-923: Integrate PoC ECS infrastructure with octopus

---

api/package-lock.json
api/package.json
ui/package-lock.json
ui/package.json

The purpose of this PR was to fix an XSS vulnerability in versions of axios prior to 1.7.8.
---
- Axios is installed at >= 1.7.8
---
---
UI
API
E2E

OC-975: Fix Cross-site Scripting (XSS)

---

infra/modules/oidc/main.tf

The deployment of OC-979 to int failed with the following message:
```
ServerlessError2: An error occurred: IamRoleLambdaExecution - Resource handler returned message: "User: arn:aws:sts::[...]:assumed-role/github-actions-role-prod-octopus/github-actions-deploy-int is not authorized to perform: iam:PutRolePolicy on resource: role octopus-api-int-***-lambdaRole because no identity-based policy allows the iam:PutRolePolicy action
```
I'm not sure why it only surfaced now, but the deployment IAM role needs permission to let serverless manage the lambda role policy upon deployment.
I've applied this change already - subsequent deploys finish correctly.
---
CI deploys can manage the lambda role via serverless.
---

OC-979-fix: Deployment role needs permissions for serverless to manage lambda role

---

api/Dockerfile
api/package-lock.json
api/package.json
api/prisma/schema.prisma

The purpose of this PR was to get around an issue where the way an optional dependency was written was making snyk think that the package-lock file was out of sync.

Change optional dependency stopping snyk from scanning

---

e2e/tests/PageModel.ts
e2e/tests/helpers/livePublication.ts
ui/src/__tests__/components/CopyButton.test.tsx
ui/src/__tests__/components/Publication/SidebarCard/General.test.tsx
ui/src/components/CopyButton/index.tsx
ui/src/components/Publication/SidebarCard/General/index.tsx
ui/src/components/index.tsx
ui/src/stores/toast.ts

The purpose of this PR was to provide users with a way to quickly grab a DOI.
---
- A button is present to the right of each DOI (“All versions” and “This version”) to copy the DOI to clipboard. This button is represented with a copy style icon
---
---
UI
E2E
---

OC-977: Button to copy DOI

---

api/src/components/user/service.ts

The purpose of this PR was to fix an error that happens when a query is submitted to the user publications endpoint with a space in it.
If such a query term is passed in to prisma's full text search, it causes a postgresql syntax error. I forgot to use the helper that converts spaces (which is used by similar endpoints for full text search).
---
Query terms containing white space can be used with the get user publications endpoint without an error.
---
---
API
---

OC-974-fix: Fix error with spaces in search query

---

ui/package-lock.json
ui/package.json

The purpose of this PR was to remediate a high severity [vulnerability](https://security.snyk.io/vuln/SNYK-JS-NEXT-8520073) in NextJS.
---
Next is installed at at least v14.2.15
---
---
UI
E2E

OC-994: Fix Missing Authorization in NextJS

---

ui/package-lock.json

The purpose of this PR was to fix a medium severity improper input validation vulnerability in the nanoid package.
Octopus's UI uses this via a chain of dependencies: NextJS -> PostCSS -> nanoid.
---
Nanoid is installed at 3.3.8 or higher.
---
---
UI
E2E

OC-987: Fix CVE-2024-55565

---

ui/package-lock.json
ui/package.json
ui/src/styles/globals.css

The purpose of this PR was to add a highlight / text selection style that applies in dark mode, as this is currently missing.
This style was present in the codebase, but due to a [bug](https://github.com/tailwindlabs/tailwindcss/pull/13379) in tailwind < 3.4.2 it wasn't applying correctly. Updating tailwind made the rule apply and I have set the background colour to be darker to meet AAA text contrast levels.
---
Highlighting text on dark mode results in text colour and background colour being inverted.
---
---
UI
E2E
---

OC-993: Text highlight colour on dark mode

---

ui/src/components/Search/Interface/index.tsx

The purpose of this PR was to make the search interface look neater when the search type select input is not displayed. Previously there was a gap between the page size select and the search bar which gave an interrupted feel.
---
On search interfaces where the search type dropdown is not displayed, the search box appears further left on the screen, and extends to the right to fill the empty space.
---
---
UI
E2E
---
Before
After

OC-990: Align search bar on public profile pages

---

api/src/components/integration/service.ts
api/src/lib/ecs.ts

The purpose of this PR was to fix an issue in the OC-925 branch that only surfaced on deployed code.
The code that triggers the ECS task was providing an invalid container override. The name property is needed as well as the command property.

OC-925-fix: Provide name with container override

---

e2e/tests/LoggedIn/search.e2e.spec.ts
ui/src/pages/search/publications/index.tsx

The purpose of this PR was to fix a bug where the date picker would close while the user is still interacting with it. This was because an action like changing month, without selecting a day, still triggers an onChange event on the input, which in turn updates the react state and pushes the date values to the querystring, reloading the page. The same applies with trying to type in a date.
The solution to this as agreed with the PO is to introduce a button to apply the selected date range filter, and only then update the react state and query string. This gives the user the time they need to select a date without the page changing and interrupting them.
---
The date picker does not close or lose focus while the user is changing it.
---
---
UI
E2E
---

OC-988: Date picker closes when different month is selected

---

api/serverless-config-default.yml
api/src/components/flag/controller.ts
api/src/lib/interface.ts
ui/src/pages/authors/[id]/index.tsx

The purpose of this PR was to fix 2 issues with the OC-817 work:
- the name of the pathParam specified in serverless.yml caused an error because it didn't match the same param after `/users/` in other endpoint paths.
- the "red flags raised by this user" area needs to show even if there are no results initially, because the user may only have raised flags that are now resolved (excluded by default), which could then be shown using the button if the area was displayed.

OC-817 fix: path param name and area showing behaviour

---

ui/next.config.js
ui/src/pages/_app.tsx
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to facilitate tracking publication views by organisational author. For example, to distinguish when an ARI publication is viewed that was authored by a particular government department.
In matomo a trigger can be set up to detect that an element with a particular ID is visible, so I have set an ID on the publication page's main section element containing the organisational user ID.
---
- Matomo tracking code is present on all publication pages
- A way of triggering a publication-view event is set up that can differentiate which organisational account owns the publication
---
---
UI
E2E

OC-986: Add Matomo tags for organisational account publications

---

ui/src/hooks/useMatomoNext.ts

The purpose of this PR was to set the `disableCookies` property on the object passed to the [@socialgouv/matomo-next](https://www.npmjs.com/package/@socialgouv/matomo-next) `init()` function. The way we had previously been doing it seems to be having the same effect, but just isn't the way the library's README recommends to do it.
---
Matomo is initialised with the `disableCookies` flag set to true.

OC-834: Set disableCookies flag on matomo

---

e2e/tests/LoggedOut/staticPages.e2e.spec.ts
e2e/tests/PageModel.ts
ui/src/components/Footer/index.tsx
ui/src/components/FunderForm/index.tsx
ui/src/components/Publication/Creation/AdditionalInformation/Table.tsx
ui/src/components/Publication/Creation/CoAuthorEntry/index.tsx
ui/src/components/Publication/Creation/LinkedItems/LinkedPublicationRow.tsx
ui/src/components/Publication/Creation/LinkedItems/LinkedTopicRow.tsx
ui/src/components/Users/HistoryTable/index.tsx
ui/src/components/Users/WorksTable/index.tsx
ui/src/config/urls.ts
ui/src/layouts/Information.tsx
ui/src/pages/accessibility.tsx
ui/src/pages/cookie-policy.tsx
ui/src/pages/privacy.tsx
ui/src/pages/terms.tsx

The purpose of this PR was to add a cookie policy page that explains the cookies in place on Octopus.
This is the same as #763 but without the banner that directs users to this page, as I've been advised that we may not need the banner. However, it would be good to get this page merged in either way.
Most of the changes other than the cookie policy page itself are correcting `space-nowrap` to `whitespace-nowrap`, or moving a section element that was common to multiple pages into the layout file that they were all using.
---
- A Cookie Policy page is present on the site (copy attached to jira ticket).
- A link to this policy is present below the “Accessibility” link in Octopus' footer
---
---
UI/E2E passed as per #763

OC-1004 (part 1): Add cookie policy

---

ui/src/components/FileUpload/index.tsx

The purpose of this PR was to fix an issue where clicking in the file upload area opens 2 file explorer windows rather than one. This was a simple fix outlined in the [readme](https://github.com/react-dropzone/react-dropzone?tab=readme-ov-file#using-label-as-root) of the library we use for this file dropzone.
---
- The file upload area only opens one file explorer window.
---
---
UI
E2E

OC-647: Image upload opens two dialogs

---

ui/src/__tests__/components/Publication/RelatedPublications/Result.test.tsx
ui/src/__tests__/components/Publication/SearchResult.test.tsx
ui/src/components/Publication/RelatedPublications/Result/index.tsx
ui/src/components/Publication/RelatedPublications/SuggestModal/index.tsx
ui/src/components/Publication/SearchResult/index.tsx
ui/src/lib/helpers.tsx

The purpose of this PR was to convert the formatting of dates from relative (e.g. "yesterday", "last year") to the specific dates (e.g. 13th Feb 2025). The relative dates could make the site seem inactive as in some cases, "last month" may be yesterday; "last year" may be a month ago, etc.
---
- Results on the publication search include the publication date in a DD MMM YYYY format (e.g. 20 January 2025)
- Publications on the author pages include the publication date in a DD MMM YYYY format (e.g. 20 January 2025)
---
---
UI
E2E
---

OC-1008: Change date format on search to dd/mmm/yyyy

---

ui/src/components/TextEditor/index.tsx

As a corresponding author, I shouldn’t need to scroll back to the top of the text editor when filling out a long main-text entry. I should be able to access formatting options at all times.
---
- On the main text field, the formatting options for the text editor follow the user’s view, remaining in the text editor at the top of the user’s window if they scrolls below the top of the text editor. 
---
---
UI
E2E
---

OC-1000: Make formatting options in text editor follow user's view

---

api/src/components/pdf/service.ts
ui/src/__tests__/components/AdditionalInformationCard.test.tsx
ui/src/components/AdditionalInformationCard/index.tsx
ui/src/lib/helpers.tsx
ui/src/pages/publications/[id]/versions/[versionId].tsx

The purpose of this PR was to add the `lang` attribute to HTML markup where a publication's language is not the default (English) and its custom content is being shown, so that assistive technology can be made aware of the content language.
---
- On the publication page, the fields listed below are marked up with the identifier for the language selected by the author during their editing process.
- On PDFs, the fields listed below are marked up with the identifier for the language selected by the author during their editing process.
- Items to mark up in the selected language are:
- title
- main text
- keywords
- description
- additional information title / description
- references
- ethical statement free text
- data permissions statement free text
- data access statement free text
- …

OC-798: A11Y Mark publication text using selected language 

---

ui/src/__tests__/components/AnnouncementBanner.test.tsx
ui/src/components/AnnouncementBanner/index.tsx
ui/src/components/Footer/index.tsx
ui/src/components/Header/index.tsx
ui/src/components/ScrollToTop/index.tsx
ui/src/components/index.tsx
ui/src/config/keys.ts
ui/src/lib/types.ts
ui/src/pages/_app.tsx
ui/src/stores/preferences.ts

The purpose of this PR was to add a generic banner for announcements on the site, such as new features, scheduled maintenance and (possibly) cookies consent.
---
- A banner can be made visible on Octopus including custom text, with a dismiss option that hides the banner until it is either removed and re-added, or its contents are changed
---
---
UI
E2E
---

OC-1012: Generic banner function

---

api/src/components/pubRouter/service.ts

The purpose of this PR was to fix an issue with the way we process affiliation data when constructing the payload to pubrouter. It seems like the code was written with the assumption that the JSON field data would come through prisma as a string, but in fact it comes out as an object, so runing `JSON.parse()` on it causes an error as that expects a string. The object is ready to use, so this change just passes it straight through, ensuring it's properly typed.
Confirmed locally that some sample metadata with affiliations is correctly constructed with this fix.

PubRouter fix: pass affiliation data in correct format

---

api/serverless-config-default.yml

The purpose of this PR was to fix an issue with the work in OC-1003 (PR #773). The newly added modules entities and katex were excluded from the serverless deployment as they were not needed outside of PDF generation, which has a separately configured deployment package. However, because they're still imported in helpers, this caused a module not found exception.

OC-1003 fix: Don't exclude entities + katex from deployment package

---

ui/src/config/values.ts
ui/src/layouts/BuildPublication.tsx
ui/src/lib/interfaces.ts
ui/src/pages/author-guide.tsx
ui/src/pages/create.tsx
ui/src/pages/faq.tsx
ui/src/pages/publications/[id]/edit.tsx

The purpose of this PR was to clarify the guidance on which publication types to use.
Because this is reusing content from the FAQ, I added it to the octopus information config values and changed that around a bit to make the properties make more sense.
---
- The author guide “Publication types” section is now titled “Choosing a publication type”
- The “Choosing a publication type” section now reads “The eight publication types in Octopus are intended to align with the research process, so select the stage which matches where you are in your work. If you would like to publish work that does not build on a publication that is already on Octopus, you will need to start with a research problem. You can publish each stage as it happens, publish when the project is finished, or adapt existing …

OC-1017: Clarify author guide publication types

---

api/package.json
api/scripts/backfillCoAuthors.ts

Publications exist on int and prod environments that are missing the corresponding author from the coauthor list. This is because we introduced the coauthor features, and made the corresponding author a coauthor by default for new publications, without updating the existing ones. As far as I have seen this only applies to seed data though.
It causes issues because certain UI components expect a populated list of coauthors.
A script is written that we will run on each environment to populate the coauthor.
---
- A script has been written that ensures every publication version has a record for the corresponding author in its coauthor list.
---
---
Simulating the issue, a publication with no coauthors - the author list on the search result is empty ("by ..."):
Running the script:
The search …

OC-378: Backfill publications without corresponding author in coauthor list

---

api/package-lock.json
api/package.json
ui/package-lock.json
ui/package.json

The purpose of this PR was to update axios to address a SSRF vulnerability in versions < 1.8.2.
---
Axios is used at 1.8.2 or greater in octopus.
---
---
UI
API
E2E

OC-1025: Fix Server-side Request Forgery (SSRF) in axios

---

api/src/components/user/__tests__/getUserPublications.test.ts
api/src/components/user/controller.ts
api/src/components/user/schema/getPublications.ts
api/src/components/user/service.ts
api/src/lib/interface.ts

The purpose of this PR was to do some back end set up for allowing octopus users to choose a draft they have access to for linking. It specified a new endpoint but it makes more sense to add an option to the existing "get user publications" endpoint to filter to initial drafts only.
The item didn't stipulate this, but non-initial drafts (version 2+) don't apply to this use case, hence the filtering by version number when the new parameter is provided.
It also needs to be able to exclude certain publications, as the user will not need to see the draft they are trying to link from in the search results.
There was version filtering in place already which is a bit confusing, but that was to return publications with at least one version matching the filter. This new filter returns publications …

OC-1014: New endpoint to fetch user's drafts

---

api/package-lock.json
api/package.json

The purpose of this PR was to fix a low severity XSS issue with dompurify. This was fixed in dompurify 3.4.2 (included in isomorphic-dompurify >=2.22.0).
---
Octopus is using the isomorphic-dompurify package at at least version 2.22.0.
---
---
API
E2E

OC-1018: Fix XSS vulnerability in dompurify

---

infra/modules/s3/main.tf

The purpose of this PR was to make use of the intelligent tiering storage class for AWS S3 that intelligently moves objects into a different archival class based on the frequency of their retrieval for a small management fee.
I've applied it to the buckets that I expect to have lots of files and variable rates of retrieval.
---
Intelligent tiering is used where beneficial.
---
---
The lifecycle rules have moved items above 128KB to intelligent tiering. Any smaller file doesn't qualify for it. This transition happens overnight each day.

OC-1026: Configure intelligent tiering for S3 buckets

---

infra/modules/codepipeline/buildspec/deploy-docker-image.yml
infra/modules/codepipeline/codepipeline.tf

The purpose of this PR was to add a trigger to the code pipeline that generates the docker image for the ARI ingest job. We need this so that whenever the code involved in the ARI ingest process changes, the docker container that will run the job will have the latest code and do the job correctly.
Tested by applying these changes to int, with the only difference being the branch that is referred to in the trigger was this development branch. The final code uses the int/prod branches as defined in the terraform `environment` var.
---
A trigger exists that will run the docker build codepipeline when the relevant branch (int or prod) is updated.
---

OC-1010: Add trigger to build ECS task docker image automatically

---

api/docs/api.yml
api/src/components/publicationVersion/service.ts

The purpose of this PR was to add a field to the GET `/publication-versions` response that is required by the UI when rendering the publication card component. This was masked until now because the card component was mocking up an author if the filter statement relying on this field (which would always have been returning an empty array) did not include the corresponding author. As a result the card was not displaying publication authors unless this field was included in the data from the API.
---
Author details are shown on the publication card component.
---
---
---
Before
After

OC-1034-fix: Include confirmedCoAuthor in response for UI

---

e2e/tests/LoggedIn/publish.e2e.spec.ts
ui/src/components/Publication/Creation/MainText.tsx
ui/src/components/TextEditor/index.tsx

The purpose of this PR was to give users a prompt for writing KaTeX formulae in the text editor.
---
- A button is present in the formatting options bar, to the right of the “code snippet” option, with a formula icon
- Clicking this option enters the text “$$Enter a KaTeX Expression$$” with the cursor placed immediately before the last two $ signs
---
---
UI
E2E
---

OC-1030: KATEX Option

---

api/prisma/seeds/local/unitTesting/publications.ts
api/src/components/coauthor/__tests__/getCoAuthors.test.ts
api/src/components/coauthor/__tests__/requestApproval.test.ts
api/src/components/coauthor/__tests__/updateAll.test.ts
api/src/components/coauthor/controller.ts
api/src/components/coauthor/service.ts
api/src/components/link/__tests__/miscFunctions.test.ts
api/src/components/publicationVersion/__tests__/updateStatus.test.ts
api/src/components/user/__tests__/getUserPublications.test.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts

The purpose of this PR was to add the effects related to the new `retainApproval` coAuthor field.
---
- A retain approval flag is present in the co-authors table (already done in #788)
- The state of this flag is checked to determine the “Publish”/”Request approval” option when the corresponding author is editing a draft, with “Publish” appearing if all co-authors have it set to retain.
- The flag is not actually checked at this point; rather, it is checked when approval would be unset (in the `resetCoAuthors` function) and prevents unsetting if true.
- The state of the retain approval flag is checked when sending emails to request approval to determine if they should be sent
---
---
API
E2E

OC-1033: Retain approval field against co-authors

---

ui/src/components/Search/PaginatedResults/index.tsx
ui/src/pages/authors/[id]/index.tsx

The purpose of this PR was to add some logging to help diagnose issues that occur with the red flag list on the author page on deployed environments, and to put in place a missed AC from a previous ticket where resolved flag results should have the flag details struck through.
---
- Logging is in place to help debug erroneous flag result sets in the UI
- Resolved flag results have the flag details struck through with " (Resolved)" added afterwards
---
---
E2E
---

OC-1056: Strikethrough resolved red flags on account page and add red flag list logging

---

api/src/components/user/__tests__/getUserPublications.test.ts
api/src/components/user/schema/getPublications.ts
api/src/components/user/service.ts
api/src/lib/interface.ts
ui/src/components/Publication/Creation/LinkedItems/LinkedPublicationCombobox/index.tsx

The purpose of this PR was to fix 2 issues with the draft linking experience:
- Filtering by a query term above 3 characters causes no results to appear
- Hypotheses can have peer reviews linked as drafts, which should not be possible
---
- Query terms above 3 characters can be used to match drafts to link to
- Only publication types that are possible to link to should be returned in the combobox
---
---
API
UI
E2E

OC-1069: Difficulty finding drafts to link

---

ui/src/__tests__/components/Publication/Card.test.tsx
ui/src/__tests__/testUtils/index.tsx
ui/src/components/Publication/Card/index.tsx

The purpose of this PR was to ensure that browse page tiles have a consistent height and appearance by limiting the author display to a certain size.
---
- Browse page tiles show only the primary author for each publication
- If any additional authors are present, the text “et al” appears after their name
- The ORCiD logo does not appear on browse page tiles  
- The author’s name is not clickable
---
---
UI
E2E
---

OC-1051: Display only first author on browse page tiles

---

ui/src/__tests__/components/Publication/Card.test.tsx
ui/src/__tests__/testUtils/index.tsx

The purpose of this PR was to update some test data to match the type it was assigned and prevent typescript errors that had made their way onto main branch.

OC-1051-fix: Test data not fitting type

---

api/package-lock.json

The purpose of this PR was to fix a vulnerability flagged by Snyk with the tar-fs package, introduced as a subdependency of  @sparticuz/chromium and puppeteer-core.
---
- tar-fs is installed at 3.0.9 or newer
- PDF generation still works as previously
---
---
API
E2E

OC-1077: Fix Improper Link Resolution Before File Access ('Link Following')

---

ui/public/security.txt

The purpose of this PR was to comply with IT-POL-14, so we need to serve at `/security.txt` the vulnerability disclosure policy URL.
---
Visiting https://octopus.ac/security.txt  serves the following content:
```md
Contact: https://www.jisc.ac.uk/contact/vulnerability-disclosure-policy
```
---

OC-1082: Add security.txt file - compliance with IT-POL-14

---

e2e/tests/LoggedIn/publish.e2e.spec.ts

The purpose of this PR was to write some end to end tests for setting a co-author's approval to be retained (or not retained) now that all the relevant code has been merged into main having been developed in pieces.
---
- Tests that cover the ACs of OC-1033 and OC-1028 are written and passing.
---
---
E2E
---

OC-1054: Write end-to-end tests for retainApproval flag

---

ui/src/components/Publication/Creation/CoAuthor.tsx

The purpose of this PR was to disable the page scrolling up and down when sorting elements in the page using the keyboard: https://docs.dndkit.com/api-documentation/sensors/keyboard
There is no configuration exposed to disable page scrolling for keyboard specifically, `autoScroll` property is managed internally by the keyboard sensor: https://docs.dndkit.com/api-documentation/context-provider#autoscroll
So the only working solution I've found is to remove the top (document element) scrollable ancestor from the `context.scrollableAncestors` list. This way it will no longer scroll the top most scrollable container.
---
- The list is sortable as normal (using the mouse and keyboard)
- The page doesn't scroll when sorting using the keyboard
---

OC-1102: DndContext custom modifier to disable page scroll on keyboard dnd

---

ui/src/components/PublicationBundle/PublicationBundleForm.tsx
ui/src/components/index.tsx
ui/src/config/urls.ts
ui/src/lib/interfaces.ts
ui/src/pages/bundles/[id].tsx
ui/src/pages/bundles/create.tsx
ui/src/pages/bundles/edit/[id].tsx
ui/src/pages/bundles/index.tsx

The purpose of this PR was to add editing support for publication bundles. It re-uses the publication picker form from https://github.com/JiscSD/octopus/pull/817 (extracted in a shared component).
---
- Clicking on "view bundle" should redirect to the bundle edit page
- I can add & remove publications from my bundle
- Saving the changes redirects back to the bundles page and the updates are reflected on the main page too.
---

OC-1045: Publication edit page

---

ui/src/pages/bundles/create.tsx

The purpose of this PR was to fix a bug where bundles/create was not showing the form. This was introduced after a bad conflict merge.
---
- bundes/create shows the form
---
---
---

OC-1111 - No interactive content in bundles/create

---

api/serverless-config-default.yml
infra/modules/bastion/main.tf
infra/modules/oidc/main.tf

The purpose of this PR was to fix the missing permissions for deploying the 2 new lambda functions (get notifications and send notification bulletin)
We merged https://github.com/JiscSD/octopus/pull/825 but the stack hasn't deployed successfully. So we added the missing permissions.

OC-1078 - Fix Notifications stack

---

README.md
api/docs/api.yml
api/src/lib/helpers.ts
e2e/tests/LoggedIn/publish.e2e.spec.ts
e2e/tests/LoggedOut/search.e2e.spec.ts
e2e/tests/PageModel.ts
ui/src/components/Publication/Creation/LinkedItems/index.tsx
ui/src/components/Publication/SimpleResult/index.tsx
ui/src/components/Publication/Visualization/index.tsx
ui/src/components/VisualPublicationFlow/index.tsx
ui/src/config/values.ts
ui/src/layouts/BuildPublication.tsx
ui/src/lib/helpers.tsx
ui/src/pages/create.tsx
ui/src/pages/octopus-aims.tsx
ui/src/pages/user-terms.tsx

The purpose of this PR was to make sure that **"Results"** should is renamed to **“Results/Sources”** and **“Real World Applications”** is renamed to **“Applications/Implications”.** In some areas, where additional explanation is needed, **“Results/Sources”** should be **“Results/Sources of evidence”** to provide further clarity
---
- “Results” is renamed to “Results/Sources” and “Real World Application” is renamed to “Applications/Implications” in the following places:
- The publication page (inc. for previews/ co-author approvals of drafts)
- The publication search page (inc. tiles and filters)
- The browse page
- Public author page
- Notifications page
- “Results” is renamed to “Results/Sources of evidence” and “Real World Application” is renamed to “Applications/Implications” in the …

OC-1112: Rename Results & Real World Applications
